export interface MasterFormatSection {
  id: string;
  title: string;
  divisionId: string;
}

export const masterFormatSections: MasterFormatSection[] = [
  // Division 01 - General Requirements
  { id: '01100', title: 'Summary', divisionId: '01' },
  { id: '01200', title: 'Price and Payment Procedures', divisionId: '01' },
  { id: '01300', title: 'Administrative Requirements', divisionId: '01' },
  { id: '01400', title: 'Quality Requirements', divisionId: '01' },
  { id: '01500', title: 'Temporary Facilities and Controls', divisionId: '01' },
  { id: '01600', title: 'Product Requirements', divisionId: '01' },
  { id: '01700', title: 'Execution Requirements', divisionId: '01' },
  { id: '01800', title: 'Facility Operation', divisionId: '01' },
  { id: '01900', title: 'Facility Decommissioning', divisionId: '01' },

  // Division 02 - Site Construction
  { id: '02050', title: 'Basic Site Materials and Methods', divisionId: '02' },
  { id: '02100', title: 'Site Remediation', divisionId: '02' },
  { id: '02200', title: 'Site Preparation', divisionId: '02' },
  { id: '02300', title: 'Earthwork', divisionId: '02' },
  { id: '02400', title: 'Tunneling, Boring, and Jacking', divisionId: '02' },
  { id: '02450', title: 'Foundation and Load-bearing Elements', divisionId: '02' },
  { id: '02500', title: 'Utility Services', divisionId: '02' },
  { id: '02600', title: 'Drainage and Containment', divisionId: '02' },
  { id: '02700', title: 'Bases, Ballasts, Pavements, and Appurtenances', divisionId: '02' },
  { id: '02800', title: 'Site Improvements and Amenities', divisionId: '02' },
  { id: '02900', title: 'Planting', divisionId: '02' },
  { id: '02950', title: 'Site Restoration and Rehabilitation', divisionId: '02' },

  // Division 03 - Concrete
  { id: '03050', title: 'Basic Concrete Materials and Methods', divisionId: '03' },
  { id: '03100', title: 'Concrete Forms and Accessories', divisionId: '03' },
  { id: '03200', title: 'Concrete Reinforcement', divisionId: '03' },
  { id: '03300', title: 'Cast-in-Place Concrete', divisionId: '03' },
  { id: '03400', title: 'Precast Concrete', divisionId: '03' },
  { id: '03500', title: 'Cementitious Decks and Underlayment', divisionId: '03' },
  { id: '03600', title: 'Grouts', divisionId: '03' },
  { id: '03700', title: 'Mass Concrete', divisionId: '03' },
  { id: '03900', title: 'Concrete Restoration and Cleaning', divisionId: '03' },

  // Division 04 - Masonry
  { id: '04050', title: 'Basic Masonry Materials and Methods', divisionId: '04' },
  { id: '04200', title: 'Masonry Units', divisionId: '04' },
  { id: '04400', title: 'Stone', divisionId: '04' },
  { id: '04500', title: 'Refractories', divisionId: '04' },
  { id: '04600', title: 'Corrosion-Resistant Masonry', divisionId: '04' },
  { id: '04700', title: 'Simulated Masonry', divisionId: '04' },
  { id: '04800', title: 'Masonry Assemblies', divisionId: '04' },
  { id: '04900', title: 'Masonry Restoration and Cleaning', divisionId: '04' },

  // Division 05 - Metals
  { id: '05050', title: 'Basic Metal Materials and Methods', divisionId: '05' },
  { id: '05100', title: 'Structural Metal Framing', divisionId: '05' },
  { id: '05200', title: 'Metal Joists', divisionId: '05' },
  { id: '05300', title: 'Metal Deck', divisionId: '05' },
  { id: '05400', title: 'Cold-Formed Metal Framing', divisionId: '05' },
  { id: '05500', title: 'Metal Fabrications', divisionId: '05' },
  { id: '05600', title: 'Hydraulic Fabrications', divisionId: '05' },
  { id: '05650', title: 'Railroad Track and Accessories', divisionId: '05' },
  { id: '05700', title: 'Ornamental Metal', divisionId: '05' },
  { id: '05800', title: 'Expansion Control', divisionId: '05' },
  { id: '05900', title: 'Metal Restoration and Cleaning', divisionId: '05' },

  // Division 06 - Wood and Plastics
  { id: '06050', title: 'Basic Materials and Methods', divisionId: '06' },
  { id: '06100', title: 'Rough Carpentry', divisionId: '06' },
  { id: '06200', title: 'Finish Carpentry', divisionId: '06' },
  { id: '06400', title: 'Architectural Woodwork', divisionId: '06' },
  { id: '06500', title: 'Structural Plastics', divisionId: '06' },
  { id: '06600', title: 'Plastic Fabrications', divisionId: '06' },
  { id: '06900', title: 'Wood and Plastic Restoration and Cleaning', divisionId: '06' },

  // Division 07 - Thermal and Moisture Protection
  { id: '07050', title: 'Basic Materials and Methods', divisionId: '07' },
  { id: '07100', title: 'Dampproofing and Waterproofing', divisionId: '07' },
  { id: '07200', title: 'Thermal Protection', divisionId: '07' },
  { id: '07300', title: 'Shingles, Roof Tiles, and Roof Coverings', divisionId: '07' },
  { id: '07400', title: 'Roofing and Siding Panels', divisionId: '07' },
  { id: '07500', title: 'Membrane Roofing', divisionId: '07' },
  { id: '07600', title: 'Flashing and Sheet Metal', divisionId: '07' },
  { id: '07700', title: 'Roof Specialties and Accessories', divisionId: '07' },
  { id: '07800', title: 'Fire and Smoke Protection', divisionId: '07' },
  { id: '07900', title: 'Joint Sealers', divisionId: '07' },

  // Division 08 - Doors and Windows
  { id: '08050', title: 'Basic Materials and Methods', divisionId: '08' },
  { id: '08100', title: 'Metal Doors and Frames', divisionId: '08' },
  { id: '08200', title: 'Wood and Plastic Doors', divisionId: '08' },
  { id: '08300', title: 'Specialty Doors', divisionId: '08' },
  { id: '08400', title: 'Entrances and Storefronts', divisionId: '08' },
  { id: '08500', title: 'Windows', divisionId: '08' },
  { id: '08600', title: 'Skylights', divisionId: '08' },
  { id: '08700', title: 'Hardware', divisionId: '08' },
  { id: '08800', title: 'Glazing', divisionId: '08' },
  { id: '08900', title: 'Glazed Curtain Wall', divisionId: '08' },

  // Division 09 - Finishes
  { id: '09050', title: 'Basic Materials and Methods', divisionId: '09' },
  { id: '09100', title: 'Metal Support Assemblies', divisionId: '09' },
  { id: '09200', title: 'Plaster and Gypsum Board', divisionId: '09' },
  { id: '09300', title: 'Tile', divisionId: '09' },
  { id: '09400', title: 'Terrazzo', divisionId: '09' },
  { id: '09500', title: 'Ceilings', divisionId: '09' },
  { id: '09600', title: 'Flooring', divisionId: '09' },
  { id: '09700', title: 'Wall Finishes', divisionId: '09' },
  { id: '09800', title: 'Acoustical Treatment', divisionId: '09' },
  { id: '09900', title: 'Paints and Coatings', divisionId: '09' },

  // Division 10 - Specialties
  { id: '10100', title: 'Visual Display Boards', divisionId: '10' },
  { id: '10150', title: 'Compartments and Cubicles', divisionId: '10' },
  { id: '10200', title: 'Louvers and Vents', divisionId: '10' },
  { id: '10240', title: 'Grilles and Screens', divisionId: '10' },
  { id: '10250', title: 'Service Walls', divisionId: '10' },
  { id: '10260', title: 'Wall and Corner Guards', divisionId: '10' },
  { id: '10270', title: 'Access Flooring', divisionId: '10' },
  { id: '10290', title: 'Pest Control', divisionId: '10' },
  { id: '10300', title: 'Fireplaces and Stoves', divisionId: '10' },
  { id: '10340', title: 'Manufactured Exterior Specialties', divisionId: '10' },
  { id: '10350', title: 'Flagpoles', divisionId: '10' },
  { id: '10400', title: 'Identification Devices', divisionId: '10' },
  { id: '10450', title: 'Pedestrian Control Devices', divisionId: '10' },
  { id: '10500', title: 'Lockers', divisionId: '10' },
  { id: '10520', title: 'Fire Protection Specialties', divisionId: '10' },
  { id: '10530', title: 'Protective Covers', divisionId: '10' },
  { id: '10550', title: 'Postal Specialties', divisionId: '10' },
  { id: '10600', title: 'Partitions', divisionId: '10' },
  { id: '10670', title: 'Storage Shelving', divisionId: '10' },
  { id: '10700', title: 'Exterior Protection', divisionId: '10' },
  { id: '10750', title: 'Telephone Specialties', divisionId: '10' },
  { id: '10800', title: 'Toilet, Bath, and Laundry Accessories', divisionId: '10' },
  { id: '10880', title: 'Scales', divisionId: '10' },
  { id: '10900', title: 'Wardrobe and Closet Specialties', divisionId: '10' },

  // Division 11 - Equipment
  { id: '11010', title: 'Maintenance Equipment', divisionId: '11' },
  { id: '11020', title: 'Security and Vault Equipment', divisionId: '11' },
  { id: '11030', title: 'Teller and Service Equipment', divisionId: '11' },
  { id: '11040', title: 'Ecclesiastical Equipment', divisionId: '11' },
  { id: '11050', title: 'Library Equipment', divisionId: '11' },
  { id: '11060', title: 'Theater and Stage Equipment', divisionId: '11' },
  { id: '11070', title: 'Instrumental Equipment', divisionId: '11' },
  { id: '11080', title: 'Registration Equipment', divisionId: '11' },
  { id: '11090', title: 'Checkroom Equipment', divisionId: '11' },
  { id: '11100', title: 'Mercantile Equipment', divisionId: '11' },
  { id: '11110', title: 'Commercial Laundry and Dry Cleaning Equipment', divisionId: '11' },
  { id: '11120', title: 'Vending Equipment', divisionId: '11' },
  { id: '11130', title: 'Audio-Visual Equipment', divisionId: '11' },
  { id: '11140', title: 'Vehicle Service Equipment', divisionId: '11' },
  { id: '11150', title: 'Parking Control Equipment', divisionId: '11' },
  { id: '11160', title: 'Loading Dock Equipment', divisionId: '11' },
  { id: '11170', title: 'Solid Waste Handling Equipment', divisionId: '11' },
  { id: '11190', title: 'Detention Equipment', divisionId: '11' },
  { id: '11200', title: 'Water Supply and Treatment Equipment', divisionId: '11' },
  { id: '11280', title: 'Hydraulic Gates and Valves', divisionId: '11' },
  { id: '11300', title: 'Fluid Waste Treatment and Disposal Equipment', divisionId: '11' },
  { id: '11400', title: 'Food Service Equipment', divisionId: '11' },
  { id: '11450', title: 'Residential Equipment', divisionId: '11' },
  { id: '11460', title: 'Unit Kitchens', divisionId: '11' },
  { id: '11470', title: 'Darkroom Equipment', divisionId: '11' },
  { id: '11480', title: 'Athletic, Recreational, and Therapeutic Equipment', divisionId: '11' },
  { id: '11500', title: 'Industrial and Process Equipment', divisionId: '11' },
  { id: '11600', title: 'Laboratory Equipment', divisionId: '11' },
  { id: '11650', title: 'Planetarium Equipment', divisionId: '11' },
  { id: '11660', title: 'Observatory Equipment', divisionId: '11' },
  { id: '11680', title: 'Office Equipment', divisionId: '11' },
  { id: '11700', title: 'Medical Equipment', divisionId: '11' },
  { id: '11780', title: 'Mortuary Equipment', divisionId: '11' },
  { id: '11850', title: 'Navigation Equipment', divisionId: '11' },
  { id: '11870', title: 'Agricultural Equipment', divisionId: '11' },
  { id: '11900', title: 'Exhibit Equipment', divisionId: '11' },

  // Division 12 - Furnishings
  { id: '12050', title: 'Fabrics', divisionId: '12' },
  { id: '12100', title: 'Art', divisionId: '12' },
  { id: '12300', title: 'Manufactured Casework', divisionId: '12' },
  { id: '12400', title: 'Furnishings and Accessories', divisionId: '12' },
  { id: '12500', title: 'Furniture', divisionId: '12' },
  { id: '12600', title: 'Multiple Seating', divisionId: '12' },
  { id: '12700', title: 'Systems Furniture', divisionId: '12' },
  { id: '12800', title: 'Interior Plants and Planters', divisionId: '12' },
  { id: '12900', title: 'Furnishings Repair and Restoration', divisionId: '12' },

  // Division 13 - Special Construction
  { id: '13010', title: 'Air-Supported Structures', divisionId: '13' },
  { id: '13020', title: 'Building Modules', divisionId: '13' },
  { id: '13030', title: 'Special Purpose Rooms', divisionId: '13' },
  { id: '13080', title: 'Sound, Vibration, and Seismic Control', divisionId: '13' },
  { id: '13090', title: 'Radiation Protection', divisionId: '13' },
  { id: '13100', title: 'Lightning Protection', divisionId: '13' },
  { id: '13110', title: 'Cathodic Protection', divisionId: '13' },
  { id: '13120', title: 'Pre-Engineered Structures', divisionId: '13' },
  { id: '13150', title: 'Swimming Pools', divisionId: '13' },
  { id: '13160', title: 'Aquariums', divisionId: '13' },
  { id: '13165', title: 'Aquatic Park Facilities', divisionId: '13' },
  { id: '13170', title: 'Tubs and Pools', divisionId: '13' },
  { id: '13175', title: 'Ice Rinks', divisionId: '13' },
  { id: '13185', title: 'Kennels and Animal Shelters', divisionId: '13' },
  { id: '13190', title: 'Site-Constructed Incinerators', divisionId: '13' },
  { id: '13200', title: 'Storage Tanks', divisionId: '13' },
  { id: '13220', title: 'Filter Underdrains and Media', divisionId: '13' },
  { id: '13230', title: 'Digester Covers and Appurtenances', divisionId: '13' },
  { id: '13240', title: 'Oxygenation Systems', divisionId: '13' },
  { id: '13260', title: 'Sludge Conditioning Systems', divisionId: '13' },
  { id: '13280', title: 'Hazardous Material Remediation', divisionId: '13' },
  { id: '13400', title: 'Measurement and Control Instrumentation', divisionId: '13' },
  { id: '13500', title: 'Recording Instrumentation', divisionId: '13' },
  { id: '13550', title: 'Transportation Control Instrumentation', divisionId: '13' },
  { id: '13600', title: 'Solar and Wind Energy Equipment', divisionId: '13' },
  { id: '13700', title: 'Security Access and Surveillance', divisionId: '13' },
  { id: '13800', title: 'Building Automation and Control', divisionId: '13' },
  { id: '13850', title: 'Detection and Alarm', divisionId: '13' },
  { id: '13900', title: 'Fire Suppression', divisionId: '13' },

  // Division 14 - Conveying Systems
  { id: '14100', title: 'Dumbwaiters', divisionId: '14' },
  { id: '14200', title: 'Elevators', divisionId: '14' },
  { id: '14300', title: 'Escalators and Moving Walks', divisionId: '14' },
  { id: '14400', title: 'Lifts', divisionId: '14' },
  { id: '14500', title: 'Material Handling', divisionId: '14' },
  { id: '14600', title: 'Hoists and Cranes', divisionId: '14' },
  { id: '14700', title: 'Turntables', divisionId: '14' },
  { id: '14800', title: 'Scaffolding', divisionId: '14' },
  { id: '14900', title: 'Transportation', divisionId: '14' },

  // Division 15 - Mechanical
  { id: '15050', title: 'Basic Mechanical Materials and Methods', divisionId: '15' },
  { id: '15100', title: 'Building Services Piping', divisionId: '15' },
  { id: '15200', title: 'Process Piping', divisionId: '15' },
  { id: '15300', title: 'Fire Protection Piping', divisionId: '15' },
  { id: '15400', title: 'Plumbing Fixtures and Equipment', divisionId: '15' },
  { id: '15500', title: 'Heat-Generation Equipment', divisionId: '15' },
  { id: '15600', title: 'Refrigeration Equipment', divisionId: '15' },
  { id: '15700', title: 'Heating, Ventilating, and Air Conditioning Equipment', divisionId: '15' },
  { id: '15800', title: 'Air Distribution', divisionId: '15' },
  { id: '15900', title: 'HVAC Instrumentation and Controls', divisionId: '15' },
  { id: '15950', title: 'Testing, Adjusting, and Balancing', divisionId: '15' },

  // Division 16 - Electrical
  { id: '16050', title: 'Basic Electrical Materials and Methods', divisionId: '16' },
  { id: '16100', title: 'Wiring Methods', divisionId: '16' },
  { id: '16200', title: 'Electrical Power', divisionId: '16' },
  { id: '16300', title: 'Transmission and Distribution', divisionId: '16' },
  { id: '16400', title: 'Low-Voltage Distribution', divisionId: '16' },
  { id: '16500', title: 'Lighting', divisionId: '16' },
  { id: '16700', title: 'Communications', divisionId: '16' },
  { id: '16800', title: 'Sound and Video', divisionId: '16' },
];
