import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'dashboard': 'Dashboard',
    'core_data': 'CORE DATA',
    'finance': 'FINANCE',
    'governance': 'GOVERNANCE',
    'utilities': 'UTILITIES',
    'project_management_plan': 'Project Management Plan',
    'resources_optimization': 'Resources & Optimization',
    'stakeholder_register': 'Stakeholder Register',
    'assumptions_log': 'Assumptions Log',
    'decision_log': 'Decision Log',
    'lessons_learned': 'Lessons Learned',
    'gantt_chart': 'Gantt Chart',
    'wbs': 'WBS',
    'boq': 'BOQ',
    'po_management': 'PO',
    'payment_certificate': 'Payment Certificate',
    'earned_value_report': 'Earned Value Report',
    'progress_reports': 'Progress Reports',
    'task_management': 'Task Management',
    'risk_opportunity_hub': 'Risk & Opportunity Hub',
    'change_management': 'Change Management',
    'meeting_management': 'Meeting Management',
    'project_files': 'Project Files',
    'settings': 'Settings',
    'admin_settings': 'Admin Settings',
    'users': 'Users',
    'contacts': 'Contacts',
    'companies': 'Companies',
    '3m_resources': '3M Resources',
    'work_packages': 'Work Packages',
    'wbs_hierarchy': 'WBS Hierarchy',
    'cost_accounts': 'Cost Accounts',
    'structure': 'Structure',
    'scheduling': 'Scheduling',
    'search_hierarchy': 'Search hierarchy...',
    'ai_generate_wbs': 'AI Generate WBS',
    'add_level': 'Add Level',
    'no_hierarchy_defined': 'No Hierarchy Defined',
    'no_hierarchy_hint': 'Start by adding major project zones or sectors to build your WBS.',
    'add_cost_account': 'Add Cost Account',
    'delete_selected': 'Delete Selected',
    'manage_cost_accounts_desc': 'Manage project-specific cost accounts and budget divisions.',
    'add_work_package': 'Add Work Package',
    'manage_work_packages_desc': 'Manage detailed work packages linked to WBS levels and Cost Accounts.',
    'projects': 'Projects',
    'search_pages': 'Search pages...',
    'search_results': 'Search Results',
    'favorites': 'Favorites',
    'quick_access_favorites': 'Quick Access Favorites',
    'archive': 'Archive',
    'new_meeting': 'New Meeting',
    'no_meetings_found': 'No meetings found',
    'adjust_filters_hint': 'Adjust your filters or search terms to find what you\'re looking for.',
    'try_searching_hint': 'Try searching for domains like "Finance" or "Schedule"',
    'risk_management': 'Risk Management',
    'technical_review': 'Technical Review',
    'owner_meeting': 'Owner Meeting',
    'general': 'General',
    'kick_off': 'Kick-off',
    'no_notes_provided': 'No summary notes provided for this meeting.',
    'no_favorites': 'No favorites yet',
    'star_pages_to_add': 'Star pages to add them here',
    'no_results_found': 'No results found',
    'hierarchy': 'HIERARCHY',
    'domains': 'DOMAINS',
    'select_project_files': 'Select a project to view files.',
    'loading': 'Loading...',
    'sign_out': 'Sign Out',
    'language': 'Language',
    'toggle_language': 'Toggle Language',
    'english': 'English',
    'arabic': 'العربية',
    'project_schedule': 'Project Schedule',
    'overall_progress': 'Overall Progress',
    'planned_cost': 'Planned Cost',
    'actual_cost': 'Actual Cost',
    'po_lines': 'PO Lines',
    'subcontractor_advances': 'Subcontractor Advances',
    'daily_reports': 'Daily Reports',
    'meetings': 'Meetings',
    'activities': 'Activities',
    'planned': 'Planned',
    'actual_on_time': 'Actual (On Time)',
    'actual_delayed': 'Actual (Delayed)',
    'activity_wbs': 'Activity / WBS',
    'start': 'Start',
    'finish': 'Finish',
    'duration': 'Duration',
    'progress': 'Progress',
    'today': 'Today',
    'expand_all': 'Expand All',
    'collapse_all': 'Collapse All',
    'add_activity': 'Add Activity',
    'columns': 'Columns',
    'print': 'Print',
    'generated': 'Generated',
    'project': 'Project',
    'select_project': 'Select Project',
    'no_projects_found': 'No projects found',
    'currency': 'Currency',
    'select_display_currency': 'Select Display Currency',
    'exchange_rate': 'Exchange Rate',
    'fetch_market_rate': 'Fetch market rate',
    'update_rate': 'Update Rate',
    'signed_in_as': 'Signed in as',
    'my_profile': 'My Profile',
    'cost_account': 'Cost Account',
    'grand_total': 'Grand Total',
    'total': 'Total',
    'execution': 'Execution',
    'configuration': 'Configuration',
    'view_gantt': 'Gantt View',
    'view_activities': 'Activity List',
    'view_milestones': 'Milestones',
    'setup_plan': 'Management Plan',
    'manage_daily_progress_logs': 'Manage and track daily construction site progress logs.',
    'search_reports': 'Search reports...',
    'new_report': 'New Daily Report',
    'meeting_minutes': 'Meeting Minutes',
    'view_meeting': 'View Meeting',
    'attendees': 'Attendees',
    'agenda': 'Agenda',
    'decisions': 'Decisions',
    'incidents': 'Incidents',
    'site_weather': 'Site Weather',
    'manpower_log': 'Manpower Log',
    'equipment_log': 'Equipment Log',
    'purchase_orders': 'Purchase Orders',
    'zone': 'Zone',
    'area': 'Area',
    'building': 'Building',
    'meetings_desc': 'The institutional memory of the project.',
    'search_meetings_placeholder': 'Search by keyword (e.g. \"HVAC\", \"Concrete\")...',
    'timeline': 'Timeline',
    'meeting_health': 'Meeting Health',
    'status': 'Status',
    'progress_summary': 'Progress Summary',
    'manpower': 'Manpower',
    'equipment': 'Equipment',
    'weather': 'Weather',
    'author': 'Author',
    'incident_summary': 'Incident Summary',
    'staff': 'Staff',
    'draft': 'Draft',
    'submitted': 'Submitted',
    'approved': 'Approved',
    'units': 'Units',
    'description': 'Description',
    'search_activities': 'Search activities or WBS...',
    'project_canvas_hub': 'Project Canvas Hub',
    'interactive_workspace': 'Interactive Workspace: Defining the project core logic.',
    'smart_integration_active': 'Smart Integration Active',
    'core_objectives': 'CORE OBJECTIVES',
    'objectives_desc': 'Primary Project Objectives...',
    'project_boundaries': 'Project Boundaries',
    'boundaries_desc': 'What\'s included and excluded?',
    'quality_assurance': 'Quality Assurance',
    'success_criteria_desc': 'How is project success measured?',
    'matrix_structure_raci': 'Matrix Structure: RACI Logic',
    'add_node': 'Add Node',
    'role_entity': 'Role / Entity',
    'responsibility': 'Responsibility',
    'accountability': 'Accountability',
    'principal_role': 'Principal Role',
    'assigned_to': 'Assigned To',
    'repopulate_from_db': 'Repopulate from Project Database',
    'financial_framework': 'Financial Framework',
    'budget_estimate_iqd': 'High-Level Budget Estimate (IQD)',
    'budget_authority_details': 'Budget Authority Details',
    'budget_limits_desc': 'Define budget limits and approval steps.',
    'formal_approvals': 'Formal Approvals',
    'print_name': 'Print Name',
    'generate_final_charter': 'Generate Final Charter',
    'auto_populate_desc': 'Auto-populates data to PMBOK Standard PDF',
    'day': 'Day',
    'week': 'Week',
    'month': 'Month',
    'quarter': 'Quarter',
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'add': 'Add',
    'actions': 'Actions',
    'name': 'Name',
    'email': 'Email',
    'role': 'Role',
    'date': 'Date',
    'type': 'Type',
    'priority': 'Priority',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'active': 'Active',
    'inactive': 'Inactive',
    'completed': 'Completed',
    'in_progress': 'In Progress',
    'pending': 'Pending',
    'on_hold': 'On Hold',
    'cancelled': 'Cancelled',
    'yes': 'Yes',
    'no': 'No',
    'back': 'Back',
    'next': 'Next',
    'submit': 'Submit',
    'update': 'Update',
    'create': 'Create',
    'search': 'Search',
    'filter': 'Filter',
    'clear': 'Clear',
    'all': 'All',
    'none': 'None',
    'management': 'Management',
    'reporting': 'Reporting',
    'boq_manager': 'BOQ Manager',
    'export_reports': 'Export Reports',
    'import_data': 'Import Data',
    'boq_summary': 'BOQ Summary',
    'completion': 'Completion %',
    'master_boq': 'Master Bill of Quantities',
    'search_items_placeholder': 'Search items...',
    'add_item': 'Add Item',
    'importing': 'Importing...',
    'qty': 'Qty',
    'unit_rate': 'Unit Rate',
    'wbs_required': 'WBS Structure Required',
    'wbs_required_hint': 'You must define your Work Breakdown Structure (WBS) before managing the Bill of Quantities.',
    'go_to_wbs': 'Go to WBS Setup',
    'project_summary': 'PROJECT SUMMARY',
    'nodes': 'NODES',
    'floor': 'Floor',
    'division': 'Division',
    'unit': 'Unit',
    'details': 'Details',
    'overview': 'Overview',
    'history': 'History',
    'comments': 'Comments',
    'attachments': 'Attachments',
    'notifications': 'Notifications',
    'profile': 'Profile',
    'logout': 'Logout',
    'login': 'Login',
    'register': 'Register',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'forgot_password': 'Forgot Password?',
    'reset_password': 'Reset Password',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'confirm_delete': 'Are you sure you want to delete this?',
    'confirm_action': 'Are you sure you want to perform this action?',
    'no_data': 'No data available',
    'required_field': 'This field is required',
    'invalid_email': 'Invalid email address',
    'password_mismatch': 'Passwords do not match',
    'save_success': 'Saved successfully',
    'delete_success': 'Deleted successfully',
    'update_success': 'Updated successfully',
    'error_message': 'Something went wrong. Please try again.',
    'boq_value_by_location': 'BOQ Value by Location',
    'view_all_boq': 'View All BOQ',
    'project_schedule_summary': 'Project Schedule Summary',
    'view_full_schedule': 'View Full Schedule',
    'view_details': 'View Details',
    'no_sub_domains_found': 'No sub-domains found for this area.',
    'project_identity': 'Project Identity',
    'objectives_milestones': 'Objectives & Milestones',
    'financials_stakeholders': 'Financials & Stakeholders',
    'governance_approvals': 'Governance & Approvals',
    'project_title': 'Project Title',
    'date_prepared': 'Date Prepared',
    'project_sponsor': 'Project Sponsor',
    'project_manager': 'Project Manager',
    'project_customer': 'Project Customer',
    'project_purpose_justification': 'Project Purpose or Justification',
    'project_description': 'Project Description',
    'high_level_requirements': 'High-Level Requirements',
    'high_level_risks': 'High-Level Risks',
    'project_objectives': 'Project Objectives',
    'success_criteria': 'Success Criteria',
    'person_approving': 'Person Approving',
    'summary_milestones': 'Summary Milestones',
    'milestone_description': 'Milestone description...',
    'due_date': 'Due Date',
    'estimated_budget': 'Estimated Budget',
    'pm_authority_level': 'Project Manager Authority Level',
    'staffing_decisions': 'Staffing Decisions',
    'budget_management_variance': 'Budget Management and Variance',
    'technical_decisions': 'Technical Decisions',
    'conflict_resolution': 'Conflict Resolution',
    'approvals': 'Approvals',
    'pm_signature': 'Project Manager Signature',
    'sponsor_signature': 'Sponsor or Originator Signature',
    'pm_name': 'Project Manager Name',
    'sponsor_name': 'Sponsor or Originator Name',
    'download_pdf': 'Download PDF',
    'save_new_version': 'Save New Version',
    'overwrite': 'Overwrite',
    'charter_updated_success': 'Charter updated successfully.',
    'milestone': 'Milestone',
    'stakeholder': 'Stakeholder',
    'high_level_risks_placeholder': 'Enter one risk per line...',
    'charter_version_history': 'Charter Version History',
    'no_history_recorded': 'No history recorded.',
    'restore': 'Restore',
    'restricted_data_link': 'Restricted Data Link',
    'pull_from_policies': 'Pull from Policies',
    'formatted': 'Formatted',
    'rate': 'Rate',
    'initialize_project': 'Initialize Project',
    'save_changes': 'Save Changes',
    'identity_identification': 'Identity & Identification',
    'project_code': 'Project Code',
    'project_location': 'Project Location',
    'admin_pin': 'Admin PIN',
    'admin_pin_hint': 'Used for authorizing critical plan overwrites.',
    'timeline_status': 'Timeline & Status',
    'start_date': 'Start Date',
    'end_date_est': 'End Date (Est.)',
    'drive_integration': 'Drive Integration',
    'drive_integration_hint': 'When you initialize this project, Zarya will automatically create a secure folder structure in Google Drive and generate the initial Project Charter PDF based on these details.',
    'project_name_code_required': 'Project Name and Code are required.',
    'project_created_success': 'Project created successfully with Google Drive workspace!',
    'project_updated_success': 'Project information updated successfully!',
    'failed_to_save_project': 'Failed to save project',
    'seed_demo_project': 'Seed Demo Project',
    'test_drive': 'Test Drive',
    'backup_codebase': 'Backup Codebase',
    'create_new_project': 'Create New Project',
    'loading_projects': 'Loading projects...',
    'access_denied': 'Access Denied',
    'no_admin_privileges': 'You do not have administrative privileges to manage projects. Please sign in with an authorized account.',
    'return_to_dashboard': 'Return to Dashboard',
    'confirm_delete_project': 'Are you sure you want to delete this project? This will only remove it from the database.',
    'project_deleted_success': 'Project deleted from database.',
    'unassigned': 'Unassigned',
    'backing_up': 'Backing up...',
    'backup_success': 'Codebase backed up successfully to Google Drive!',
    'backup_failed': 'Backup failed',
    'drive_connected_success': 'Success! Connected to Google Drive.',
    'connection_failed': 'Connection Failed!',
    'demo_project_added_success': 'Demo project added to database and Google Drive structure initialized!',
    'failed_to_add_demo_project': 'Failed to add demo project',
    'project_executive_dashboard': 'Project Executive Dashboard',
    'loading_project_data': 'Loading project data...',
    'no_project_selected': 'No project selected or found.',
    'select_project_hint': 'Please select a project from the header or create a new one.',
    'boq_total': 'BOQ Total',
    'quality_compliance': 'Quality Compliance',
    'strategic_performance': 'Strategic Performance',
    'view_full_report': 'View Full Report',
    'overall_completion': 'Overall Completion',
    'engineering_design': 'Engineering & Design',
    'procurement_logistics': 'Procurement & Logistics',
    'site_preparation': 'Site Preparation',
    'main_construction': 'Main Construction',
    'critical_alerts': 'Critical Alerts',
    'critical_action_required': 'Critical Action Required',
    'project_warning': 'Project Warning',
    'all_systems_operational': 'All systems operational',
    'project_activities': 'Project Activities',
    'generate_from_boq': 'Generate from BOQ',
    'add_new_work_package': 'Add New Work Package',
    'masterformat_suggestions': 'MasterFormat 16 Cost Accounts Suggestions',
    'select_division_first': 'Please select a division first.',
    'create_package': 'Create Package',
    'no_activities_found': 'No Activities Found',
    'no_activities_hint': 'Click "Add Activity" or "Generate from BOQ" to build your activity list.',
    'work_package': 'Work Package',
    'convert_to_po': 'Convert to PO',
    'assignee': 'Assignee',
    'planned_dates': 'Planned Dates',
    'activity_type': 'Activity Type',
    'confirm_delete_activity': 'Are you sure you want to delete this activity?',
    'activities_generated_success': 'Activities generated from BOQ successfully.',
    'po_created_success': 'Purchase Order created successfully.',
    'gov': 'Governance',
    'scope': 'Scope',
    'sched': 'Schedule',
    'fin': 'Finance',
    'stak': 'Stakeholders',
    'res': 'Resources',
    'risk': 'Risk',
    'drive': 'Drive Explorer',
    'admin': 'Admin Settings',
    '1.0': 'Initiating Focus Area',
    '1.1': 'Governance Domain',
    '1.2': 'Stakeholders Domain',
    '2.0': 'Planning Focus Area',
    '2.1': 'Governance Domain',
    '1.1.1': 'Project Charter',
    '1.1.2': 'Project Policies & Procedures',
    '2.1.2': 'Project Management Plan',
    '2.1.1': 'Change Management Plan',
    '2.1.3': 'Quality Management Plan',
    '2.1.6': 'Communications Management Plan',
    '2.1.7': 'Stakeholder Management Plan',
    '2.1.8': 'Requirements Management Plan',
    '2.1.9': 'Scope Management Plan',
    '2.1.10': 'Human Resource Management Plan',
    '2.1.11': 'Schedule Management Plan',
    '2.1.12': 'Cost Management Plan',
    '2.1.13': 'Procurement Management Plan',
    '2.1.14': 'Risk Management Plan',
    '2.1.4': 'Quality Metrics',
    '2.1.5': 'Assumption and Constraint Log',
    '2.5': 'Stakeholders Domain',
    '1.2.1': 'Stakeholder Register',
    '1.2.2': 'Stakeholder Analysis Matrix',
    '2.2': 'Scope Domain',
    '2.2.3': 'Project Scope Statement',
    '2.2.4': 'Requirements Documentation',
    '2.2.6': 'Requirements Traceability Matrix',
    '2.2.9': 'WBS',
    '2.3': 'Project Schedule',
    '2.4': 'Finance Domain',
    '2.4.0': 'BOQ',
    '2.6': 'Resources Domain',
    '2.6.1': 'Activity Resource Requirements',
    '2.6.21': 'Task Management',
    '2.6.22': 'Meetings & Minutes',
    '2.6.4': 'Resource Breakdown Structure',
    '2.6.5': 'Responsibility Assignment Matrix',
    '2.6.6': 'Roles and Responsibilities',
    '2.6.7': 'Source Selection Criteria',
    '2.7': 'Risk & Opportunity Hub',
    '2.7.5': 'Risk Register',
    '2.7.1': 'Probability and Impact Assessment',
    '2.7.2': 'Probability and Impact Matrix',
    '3.0': 'Executing Focus Area',
    '3.1': 'Governance Domain',
    '3.1.3': 'Decision Log',
    '3.1.4': 'Quality Audit',
    '3.2': 'Stakeholders Domain',
    '3.3': 'Resources Domain',
    '3.4': 'Change Management Hub',
    '3.3.1': 'Team Directory',
    '3.3.5': 'Team Operating Agreement',
    '3.3.2': 'Team Member Performance Assessment',
    '3.3.6': 'Team Performance Assessment',
    '3.3.4': 'Supplier Master Register',
    'vendor_evaluation': 'Supplier Evaluation',
    'add_new_supplier': 'Register New Supplier',
    'edit_supplier_profile': 'Edit Supplier Profile',
    'add_supplier': 'Add Supplier',
    'supplier_code': 'Supplier Code',
    'legal_supplier_name': 'Legal Supplier Name',
    'supplier_name': 'Supplier Name',
    'discipline': 'Discipline',
    'discipline_masterformat': 'Discipline (MASTERFORMAT)',
    'operational_status': 'Operational Status',
    'register_supplier': 'Register Supplier',
    'update_supplier': 'Update Supplier',
    'add_company': 'Add New Company',
    'edit_company': 'Edit Company',
    'company_details_desc': 'Enter company details below.',
    'company_name': 'Company Name',
    'company_name_placeholder': 'e.g. Zarya Construction',
    'type_main': 'Main (Zarya)',
    'type_supplier': 'Supplier',
    'type_stakeholder': 'Stakeholder',
    'type_other': 'Other',
    'save_company': 'Save Company',
    'address': 'Address',
    'phone': 'Phone',
    'website': 'Website',
    'search_suppliers': 'Search by Supplier Name, Code or Discipline...',
    'po_total': 'PO Total',
    'paid': 'Paid',
    'balance': 'Balance',
    'supplier_profile': 'Supplier Profile',
    'supplier_details': 'Supplier Details',
    'download_statement': 'Download Full Statement',
    'no_pos_found': 'No Purchase Orders found for this supplier.',
    'vendor_stats': 'Supplier Stats',
    '3.3.3': 'Progress Reports',
    '4.0': 'Monitoring Focus Area',
    '4.1': 'Governance Domain',
    '4.1.2': 'Deliverable Acceptance',
    '4.2': 'Finance Domain',
    '4.2.5': 'PO Control Dashboard',
    '4.2.6': 'PO Management',
    '4.2.4': 'Cumulative PO Tracking',
    '4.2.3': 'Payment Certificate',
    '4.2.1': 'Contractor Status Report',
    '4.2.2': 'Earned Value Status Report',
    '4.3': 'Stakeholders Domain',
    '4.3.1': 'Project Performance Report',
    '4.3.2': 'Variance Analysis',
    '4.4': 'Risk Domain',
    '4.4.1': 'Risk Audit',
    '5.0': 'Closing Focus Area',
    '5.1': 'Governance Domain',
    '5.1.1': 'Lessons Learned Register',
    '5.1.2': 'Project Close Out',
    '5.2': 'Finance Domain',
    '5.2.1': 'Contract Close Out',
    '5.2.2': 'Procurement Audit',
    'admin-users': 'User Management',
    'admin-projects': 'Project Management',
    'admin-companies': 'Company Directory',
    'admin-contacts': 'Contact Directory',
    'domain_docs_forms': 'Domain Documentation & Forms',
    'project_logs': 'Project Logs',
    'initializing_zarya': 'Initializing Zarya...',
    'domain_performance': 'Domain Performance',
    'actual': 'Actual',
    'no_chart_data': 'No chart data available for this domain.',
    'domain_alerts': 'Domain Alerts',
    'no_active_alerts': 'No active alerts',
    'welcome_back': 'Welcome Back',
    'sign_in_desc': 'Sign in to access your project management workspace and Google Drive integration.',
    'secure': 'Secure',
    'sign_in_google': 'Sign in with Google',
    'terms_privacy': 'By signing in, you agree to our Terms of Service and Privacy Policy.',
    'enterprise_security': 'Enterprise Grade Security',
    'project_management_processes': 'Project Management Processes and Tailoring Decisions',
    'process_tools_techniques': 'Process Tools and Techniques',
    'variances_baseline_management': 'Variances and Baseline Management',
    'project_reviews': 'Project Reviews',
    'phase': 'Phase',
    'key_deliverables': 'Key Deliverables',
    'knowledge_area': 'Knowledge Area',
    'processes': 'Processes',
    'tailoring_decisions': 'Tailoring Decisions',
    'tools_techniques': 'Tools and Techniques',
    'scope_variance': 'Scope Variance',
    'schedule_variance': 'Schedule Variance',
    'cost_variance': 'Cost Variance',
    'scope_baseline_management': 'Scope Baseline Management',
    'schedule_baseline_management': 'Schedule Baseline Management',
    'cost_baseline_management': 'Cost Baseline Management',
    'governance_plans': 'Governance Plans',
    'plan_integration': 'Plan Integration',
    'plan_integration_desc': 'Management plans are integrated to ensure consistent baseline management across all project domains.',
    'management_plans': 'Management Plans',
    'policies_procedures': 'Policies & Procedures',
    'schedule': 'Schedule',
    'resource_optimization_hub': 'Resources & Optimization Hub',
    'resource_plan': 'Resource Plan',
    'resource_structure': 'Resource Structure',
    'responsibility_matrix': 'Responsibility Matrix',
    'job_descriptions': 'Job Descriptions',
    'optimization': 'Optimization',
    'export_landscape_pdf': 'Export Landscape PDF',
    'ram_raci_matrix': 'RAM / RACI Matrix',
    'intersection_wbs_personnel': 'Intersection of WBS work packages and assigned personnel.',
    'responsible': 'Responsible',
    'accountable': 'Accountable',
    'consulted': 'Consulted',
    'informed': 'Informed',
    'accountable_requires_definition': 'Accountable (A) requires approved Role definition',
    'risk_register': 'Risk Register',
    'risk_assessment': 'Risk Assessment',
    'detailed_risk_sheets': 'Detailed Risk Sheets',
    'issue_log': 'Issue Log',
    'risk_audit': 'Risk Audit',
    'loading_risk_hub': 'Loading Risk Hub...',
    'change_management_hub': 'Change Management Hub',
    'total_change_requests': 'Total Change Requests',
    'approved_variations': 'Approved Variations',
    'pending_review': 'Pending Review',
    '6': 'Resources_Domain',
    '7': 'Risk_Domain',
    'total_cost_impact': 'Total Cost Impact',
    'change_request_register': 'Change Request Register',
    'new_request': 'New Request',
    'description_of_change': 'Description of Change',
    'justification': 'Justification',
    'financial_impact': 'Financial Impact',
    'time_impact_days': 'Time Impact (Days)',
    'variation_items': 'Variation Items',
    'net_impact': 'Net Impact',
    'new_contract_total': 'New Contract Total',
    'original_value': 'Original Value',
    'edit_request': 'Edit Request',
    'no_change_requests_found': 'No change requests found',
    'old_qty': 'Old Qty',
    'new_qty': 'New Qty',
    'in_review': 'In Review',
    'quantity_cost': 'Quantity/Cost',
    'time': 'Time',
    'quality': 'Quality',
    'other': 'Other',
    'preparer': 'Preparer',
    'contractor': 'Contractor',
    'change_request_form': 'CHANGE REQUEST FORM',
    'dom_gov': 'Governance Domain',
    'dom_scope': 'Scope Domain',
    'dom_sched': 'Schedule Domain',
    'dom_fin': 'Finance Domain',
    'dom_stake': 'Stakeholders Domain',
    'dom_res': 'Resources Domain',
    'dom_risk': 'Risk Domain',
    'team_directory': 'Team Directory',
    'operating_agreement': 'Operating Agreement',
    'performance_assessment': 'Performance Assessment',
  },
  ar: {
    'dashboard': 'لوحة القيادة',
    'core_data': 'البيانات الأساسية',
    'finance': 'المالية',
    'governance': 'الحوكمة',
    'utilities': 'الأدوات المساعدة',
    'project_management_plan': 'خطة إدارة المشروع',
    'resources_optimization': 'الموارد والتحسين',
    'stakeholder_register': 'سجل أصحاب المصلحة',
    'assumptions_log': 'سجل الافتراضات',
    'decision_log': 'سجل القرارات',
    'lessons_learned': 'الدروس المستفادة',
    'gantt_chart': 'مخطط جانت',
    'wbs': 'هيكل تقسيم العمل',
    'boq': 'جدول الكميات',
    'po_management': 'PO',
    'payment_certificate': 'شهادة الدفع',
    'earned_value_report': 'تقرير القيمة المكتسبة',
    'progress_reports': 'تقارير التقدم',
    'task_management': 'إدارة المهام',
    'risk_opportunity_hub': 'مركز المخاطر والفرص',
    'change_management': 'إدارة التغيير',
    'meeting_management': 'إدارة الاجتماعات',
    'project_files': 'ملفات المشروع',
    'settings': 'الإعدادات',
    'admin_settings': 'إعدادات المسؤول',
    'users': 'المستخدمين',
    'contacts': 'جهات الاتصال',
    'companies': 'الشركات',
    '3m_resources': 'موارد 3M',
    'work_packages': 'حزم العمل',
    'wbs_hierarchy': 'الهيكل الهرمي للمشروع',
    'cost_accounts': 'حسابات التكلفة',
    'structure': 'الهيكل',
    'scheduling': 'الجدولة',
    'search_hierarchy': 'البحث في التسلسل الهرمي...',
    'ai_generate_wbs': 'توليد هيكل العمل بالذكاء الاصطناعي',
    'add_level': 'إضافة مستوى',
    'no_hierarchy_defined': 'لم يتم تعريف تسلسل هرمي',
    'no_hierarchy_hint': 'ابدأ بإضافة مناطق أو قطاعات المشروع الرئيسية لبناء هيكل تقسيم العمل الخاص بك.',
    'add_cost_account': 'إضافة حساب تكلفة',
    'delete_selected': 'حذف المحدد',
    'manage_cost_accounts_desc': 'إدارة حسابات التكلفة وأقسام الميزانية الخاصة بالمشروع.',
    'add_work_package': 'إضافة حزمة عمل',
    'manage_work_packages_desc': 'إدارة حزم العمل التفصيلية المرتبطة بمستويات هيكل تقسيم العمل وحسابات التكلفة.',
    'projects': 'المشاريع',
    'search_pages': 'البحث في الصفحات...',
    'search_results': 'نتائج البحث',
    'favorites': 'المفضلة',
    'quick_access_favorites': 'الوصول السريع للمفضلة',
    'archive': 'أرشيف',
    'new_meeting': 'اجتماع جديد',
    'no_meetings_found': 'لم يتم العثور على اجتماعات',
    'adjust_filters_hint': 'قم بتعديل المرشحات أو مصطلحات البحث للعثور على ما تبحث عنه.',
    'try_searching_hint': 'حاول البحث عن مجالات مثل "المالية" أو "الجدول الزمني"',
    'risk_management': 'إدارة المخاطر',
    'technical_review': 'مراجعة فنية',
    'owner_meeting': 'اجتماع المالك',
    'general': 'عام',
    'kick_off': 'انطلاق المشروع',
    'no_notes_provided': 'لم يتم تقديم ملاحظات ملخصة لهذا الاجتماع.',
    'no_favorites': 'لا توجد صفحات مفضلة بعد',
    'star_pages_to_add': 'اضف نجمة للصفحات لتظهر هنا',
    'no_results_found': 'لم يتم العثور على نتائج',
    'hierarchy': 'التسلسل الهرمي',
    'domains': 'المجالات',
    'select_project_files': 'اختر مشروعاً لعرض الملفات.',
    'loading': 'جاري التحميل...',
    'sign_out': 'تسجيل الخروج',
    'language': 'اللغة',
    'toggle_language': 'تغيير اللغة',
    'english': 'English',
    'arabic': 'العربية',
    'project_schedule': 'الجدول الزمني للمشروع',
    'overall_progress': 'التقدم الإجمالي',
    'planned_cost': 'التكلفة المخططة',
    'actual_cost': 'التكلفة الفعلية',
    'po_lines': 'بنود أمر الشراء',
    'subcontractor_advances': 'سلف مقاولي الباطن',
    'daily_reports': 'التقارير اليومية',
    'meetings': 'الاجتماعات',
    'activities': 'الأنشطة',
    'planned': 'مخطط',
    'actual_on_time': 'فعلي (في الوقت)',
    'actual_delayed': 'فعلي (متأخر)',
    'activity_wbs': 'النشاط / هيكل تقسيم العمل',
    'start': 'البداية',
    'finish': 'النهاية',
    'duration': 'المدة',
    'progress': 'التقدم',
    'today': 'اليوم',
    'expand_all': 'توسيع الكل',
    'collapse_all': 'طي الكل',
    'add_activity': 'إضافة نشاط',
    'columns': 'الأعمدة',
    'print': 'طباعة',
    'generated': 'تم الإنشاء في',
    'project': 'المشروع',
    'select_project': 'اختر مشروعاً',
    'no_projects_found': 'لم يتم العثور على مشاريع',
    'currency': 'العملة',
    'select_display_currency': 'اختر عملة العرض',
    'exchange_rate': 'سعر الصرف',
    'fetch_market_rate': 'جلب سعر السوق',
    'update_rate': 'تحديث السعر',
    'signed_in_as': 'تم تسجيل الدخول باسم',
    'my_profile': 'ملفي الشخصي',
    'cost_account': 'حساب التكلفة',
    'grand_total': 'الإجمالي الكلي',
    'total': 'الإجمالي',
    'execution': 'التنفيذ',
    'configuration': 'الإعدادات',
    'view_gantt': 'عرض مخطط جانت',
    'view_activities': 'قائمة الأنشطة',
    'view_milestones': 'المعالم الرئيسية',
    'setup_plan': 'خطة الإدارة',
    'manage_daily_progress_logs': 'إدارة وتتبع سجلات التقدم اليومية في موقع العمل.',
    'search_reports': 'البحث في التقارير...',
    'new_report': 'تقرير يومي جديد',
    'meeting_minutes': 'محاضر الاجتماعات',
    'view_meeting': 'عرض الاجتماع',
    'attendees': 'الحاضرون',
    'agenda': 'جدول الأعمال',
    'decisions': 'القرارات',
    'incidents': 'الحوادث',
    'site_weather': 'حالة الطقس في الموقع',
    'manpower_log': 'سجل القوى العاملة',
    'equipment_log': 'سجل المعدات',
    'purchase_orders': 'أوامر الشراء',
    'zone': 'زون / قطاع',
    'area': 'منطقة',
    'building': 'مبنى',
    'meetings_desc': 'الذاكرة المؤسسية للمشروع.',
    'search_meetings_placeholder': 'البحث بالكلمات المفتاحية (مثلاً: "تكييف"، "خرسانة")...',
    'timeline': 'الخط الزمني',
    'meeting_health': 'صحة الاجتماع',
    'status': 'الحالة',
    'progress_summary': 'ملخص التقدم',
    'manpower': 'القوى العاملة',
    'equipment': 'المعدات',
    'weather': 'الطقس',
    'author': 'المؤلف',
    'incident_summary': 'ملخص الحوادث',
    'staff': 'موظف',
    'draft': 'مسودة',
    'submitted': 'تم الإرسال',
    'approved': 'معتمد',
    'units': 'وحدة',
    'description': 'الوصف',
    'search_activities': 'البحث في الأنشطة...',
    'project_canvas_hub': 'مركز لوحة المشروع',
    'interactive_workspace': 'مساحة عمل تفاعلية: تحديد المنطق الأساسي للمشروع.',
    'smart_integration_active': 'التكامل الذكي نشط',
    'core_objectives': 'الأهداف الأساسية',
    'objectives_desc': 'أهداف المشروع الأساسية...',
    'project_boundaries': 'حدود المشروع',
    'boundaries_desc': 'ما الذي تم تضمينه واستبعاده؟',
    'quality_assurance': 'ضمان الجودة',
    'success_criteria_desc': 'كيف يتم قياس نجاح المشروع؟',
    'matrix_structure_raci': 'هيكل المصفوفة: منطق RACI',
    'add_node': 'إضافة عقدة',
    'role_entity': 'الدور / الكيان',
    'responsibility': 'المسؤولية',
    'accountability': 'المساءلة',
    'principal_role': 'الدور الرئيسي',
    'assigned_to': 'مكلف لـ',
    'repopulate_from_db': 'إعادة التعبئة من قاعدة بيانات المشروع',
    'financial_framework': 'الإطار المالي',
    'budget_estimate_iqd': 'تقدير الميزانية عالي المستوى (دينار عراقي)',
    'budget_authority_details': 'تفاصيل صلاحيات الميزانية',
    'budget_limits_desc': 'تحديد حدود الميزانية وخطوات الموافقة.',
    'formal_approvals': 'الموافقات الرسمية',
    'print_name': 'الاسم المطبوع',
    'generate_final_charter': 'إنشاء الميثاق النهائي',
    'auto_populate_desc': 'تعبئة البيانات تلقائياً في ملف PDF بمعايير PMBOK',
    'day': 'يوم',
    'week': 'أسبوع',
    'month': 'شهر',
    'quarter': 'ربع سنة',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'edit': 'تعديل',
    'delete': 'حذف',
    'add': 'إضافة',
    'actions': 'الإجراءات',
    'name': 'الاسم',
    'email': 'البريد الإلكتروني',
    'role': 'الدور',
    'date': 'التاريخ',
    'type': 'النوع',
    'priority': 'الأولوية',
    'high': 'عالية',
    'medium': 'متوسطة',
    'low': 'منخفضة',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'completed': 'مكتمل',
    'in_progress': 'قيد التنفيذ',
    'pending': 'قيد الانتظار',
    'on_hold': 'متوقف مؤقتاً',
    'cancelled': 'ملغي',
    'yes': 'نعم',
    'no': 'لا',
    'back': 'رجوع',
    'next': 'التالي',
    'submit': 'إرسال',
    'update': 'تحديث',
    'create': 'إنشاء',
    'search': 'بحث',
    'filter': 'تصفية',
    'clear': 'مسح',
    'all': 'الكل',
    'none': 'لا شيء',
    'management': 'الإدارة',
    'reporting': 'التقارير',
    'boq_manager': 'مدير جدول الكميات',
    'export_reports': 'تصدير التقارير',
    'import_data': 'استيراد البيانات',
    'boq_summary': 'ملخص جدول الكميات',
    'completion': 'نسبة الإنجاز',
    'master_boq': 'جدول الكميات الرئيسي',
    'search_items_placeholder': 'البحث عن البنود...',
    'add_item': 'إضافة بند',
    'importing': 'جاري الاستيراد...',
    'qty': 'الكمية',
    'unit_rate': 'سعر الوحدة',
    'wbs_required': 'مطلوب هيكل تقسيم العمل',
    'wbs_required_hint': 'يجب عليك تحديد هيكل تقسيم العمل (WBS) الخاص بك قبل إدارة جدول الكميات.',
    'go_to_wbs': 'اذهب إلى إعداد WBS',
    'project_summary': 'ملخص المشروع',
    'nodes': 'عقد',
    'floor': 'طابق',
    'division': 'قسم',
    'unit': 'وحدة',
    'details': 'التفاصيل',
    'overview': 'نظرة عامة',
    'history': 'السجل',
    'comments': 'التعليقات',
    'attachments': 'المرفقات',
    'notifications': 'التنبيهات',
    'profile': 'الملف الشخصي',
    'logout': 'تسجيل الخروج',
    'login': 'تسجيل الدخول',
    'register': 'تسجيل',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'forgot_password': 'نسيت كلمة المرور؟',
    'reset_password': 'إعادة تعيين كلمة المرور',
    'error': 'خطأ',
    'success': 'نجاح',
    'warning': 'تحذير',
    'info': 'معلومات',
    'confirm_delete': 'هل أنت متأكد أنك تريد الحذف؟',
    'confirm_action': 'هل أنت متأكد أنك تريد القيام بهذا الإجراء؟',
    'no_data': 'لا توجد بيانات متاحة',
    'required_field': 'هذا الحقل مطلوب',
    'invalid_email': 'بريد إلكتروني غير صالح',
    'password_mismatch': 'كلمات المرور غير متطابقة',
    'save_success': 'تم الحفظ بنجاح',
    'delete_success': 'تم الحذف بنجاح',
    'update_success': 'تم التحديث بنجاح',
    'error_message': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
    'boq_value_by_location': 'قيمة جدول الكميات حسب الموقع',
    'view_all_boq': 'عرض كامل جدول الكميات',
    'project_schedule_summary': 'ملخص الجدول الزمني للمشروع',
    'view_full_schedule': 'عرض الجدول الزمني الكامل',
    'view_details': 'عرض التفاصيل',
    'no_sub_domains_found': 'لم يتم العثور على مجالات فرعية لهذه المنطقة.',
    'project_identity': 'هوية المشروع',
    'objectives_milestones': 'الأهداف والمعالم',
    'financials_stakeholders': 'المالية وأصحاب المصلحة',
    'governance_approvals': 'الحوكمة والاعتمادات',
    'project_title': 'عنوان المشروع',
    'date_prepared': 'تاريخ الإعداد',
    'project_sponsor': 'راعي المشروع',
    'project_manager': 'مدير المشروع',
    'project_customer': 'عميل المشروع',
    'project_purpose_justification': 'الغرض من المشروع أو مبرراته',
    'project_description': 'وصف المشروع',
    'high_level_requirements': 'المتطلبات عالية المستوى',
    'high_level_risks': 'المخاطر عالية المستوى',
    'project_objectives': 'أهداف المشروع',
    'success_criteria': 'معايير النجاح',
    'person_approving': 'الشخص المعتمد',
    'summary_milestones': 'ملخص المعالم الرئيسية',
    'milestone_description': 'وصف المعلم...',
    'due_date': 'تاريخ الاستحقاق',
    'estimated_budget': 'الميزانية التقديرية',
    'pm_authority_level': 'مستوى صلاحية مدير المشروع',
    'staffing_decisions': 'قرارات التوظيف',
    'budget_management_variance': 'إدارة الميزانية والانحرافات',
    'technical_decisions': 'القرارات الفنية',
    'conflict_resolution': 'حل النزاعات',
    'approvals': 'الاعتمادات',
    'pm_signature': 'توقيع مدير المشروع',
    'sponsor_signature': 'توقيع الراعي أو المنشئ',
    'pm_name': 'اسم مدير المشروع',
    'sponsor_name': 'اسم الراعي أو المنشئ',
    'download_pdf': 'تحميل PDF',
    'save_new_version': 'حفظ نسخة جديدة',
    'overwrite': 'استبدال',
    'charter_updated_success': 'تم تحديث الميثاق بنجاح.',
    'milestone': 'معلم رئيسي',
    'stakeholder': 'صاحب مصلحة',
    'high_level_risks_placeholder': 'أدخل مخاطرة واحدة في كل سطر...',
    'charter_version_history': 'سجل نسخ الميثاق',
    'no_history_recorded': 'لم يتم تسجيل أي سجل.',
    'restore': 'استعادة',
    'restricted_data_link': 'رابط بيانات مقيد',
    'pull_from_policies': 'سحب من السياسات',
    'formatted': 'منسق',
    'rate': 'سعر',
    'initialize_project': 'تهيئة المشروع',
    'save_changes': 'حفظ التغييرات',
    'identity_identification': 'الهوية والتعريف',
    'project_code': 'رمز المشروع',
    'project_location': 'موقع المشروع',
    'admin_pin': 'رمز المسؤول (PIN)',
    'admin_pin_hint': 'يستخدم لتفويض عمليات استبدال الخطط الحرجة.',
    'timeline_status': 'الجدول الزمني والحالة',
    'start_date': 'تاريخ البدء',
    'end_date_est': 'تاريخ الانتهاء (تقديري)',
    'drive_integration': 'تكامل درايف',
    'drive_integration_hint': 'عند تهيئة هذا المشروع، سيقوم زاريا تلقائياً بإنشاء هيكل مجلد آمن في جوجل درايف وإنشاء ملف ميثاق المشروع الأولي بناءً على هذه التفاصيل.',
    'project_name_code_required': 'اسم المشروع ورمزه مطلوبان.',
    'project_created_success': 'تم إنشاء المشروع بنجاح مع مساحة عمل جوجل درايف!',
    'project_updated_success': 'تم تحديث معلومات المشروع بنجاح!',
    'failed_to_save_project': 'فشل في حفظ المشروع',
    'seed_demo_project': 'بذر مشروع تجريبي',
    'test_drive': 'اختبار درايف',
    'backup_codebase': 'نسخ احتياطي للكود',
    'create_new_project': 'إنشاء مشروع جديد',
    'loading_projects': 'جاري تحميل المشاريع...',
    'access_denied': 'تم رفض الوصول',
    'no_admin_privileges': 'ليس لديك امتيازات إدارية لإدارة المشاريع. يرجى تسجيل الدخول بحساب مخول.',
    'return_to_dashboard': 'العودة إلى لوحة القيادة',
    'confirm_delete_project': 'هل أنت متأكد أنك تريد حذف هذا المشروع؟ سيؤدي هذا فقط إلى إزالته من قاعدة البيانات.',
    'project_deleted_success': 'تم حذف المشروع من قاعدة البيانات.',
    'unassigned': 'غير معين',
    'backing_up': 'جاري النسخ الاحتياطي...',
    'backup_success': 'تم نسخ قاعدة الكود احتياطياً بنجاح إلى جوجل درايف!',
    'backup_failed': 'فشل النسخ الاحتياطي',
    'drive_connected_success': 'نجاح! تم الاتصال بجوجل درايف.',
    'connection_failed': 'فشل الاتصال!',
    'demo_project_added_success': 'تم إضافة المشروع التجريبي إلى قاعدة البيانات وتهيئة هيكل جوجل درايف!',
    'failed_to_add_demo_project': 'فشل في إضافة المشروع التجريبي',
    'project_executive_dashboard': 'لوحة القيادة التنفيذية للمشروع',
    'loading_project_data': 'جاري تحميل بيانات المشروع...',
    'no_project_selected': 'لم يتم اختيار أو العثور على أي مشروع.',
    'select_project_hint': 'يرجى اختيار مشروع من القائمة العلوية أو إنشاء مشروع جديد.',
    'boq_total': 'إجمالي جدول الكميات',
    'quality_compliance': 'الامتثال للجودة',
    'strategic_performance': 'الأداء الاستراتيجي',
    'view_full_report': 'عرض التقرير الكامل',
    'overall_completion': 'الإنجاز الكلي',
    'engineering_design': 'الهندسة والتصميم',
    'procurement_logistics': 'المشتريات والخدمات اللوجستية',
    'site_preparation': 'تجهيز الموقع',
    'main_construction': 'الإنشاءات الرئيسية',
    'critical_alerts': 'تنبيهات حرجة',
    'critical_action_required': 'مطلوب إجراء حرج',
    'project_warning': 'تحذير المشروع',
    'all_systems_operational': 'جميع الأنظمة تعمل بشكل طبيعي',
    'project_activities': 'أنشطة المشروع',
    'generate_from_boq': 'توليد من جدول الكميات',
    'add_new_work_package': 'إضافة حزمة عمل جديدة',
    'masterformat_suggestions': 'اقتراحات حسابات التكلفة MasterFormat 16',
    'select_division_first': 'يرجى اختيار قسم أولاً.',
    'create_package': 'إنشاء حزمة',
    'no_activities_found': 'لم يتم العثور على أنشطة',
    'no_activities_hint': 'انقر على "إضافة نشاط" أو "توليد من جدول الكميات" لبناء قائمة الأنشطة الخاصة بك.',
    'work_package': 'حزمة العمل',
    'convert_to_po': 'تحويل إلى أمر شراء',
    'assignee': 'المكلف',
    'planned_dates': 'التواريخ المخططة',
    'activity_type': 'نوع النشاط',
    'confirm_delete_activity': 'هل أنت متأكد أنك تريد حذف هذا النشاط؟',
    'activities_generated_success': 'تم توليد الأنشطة من جدول الكميات بنجاح.',
    'po_created_success': 'تم إنشاء أمر الشراء بنجاح.',
    'gov': 'الحوكمة',
    'scope': 'النطاق',
    'sched': 'الجدول الزمني',
    'fin': 'المالية',
    'stak': 'أصحاب المصلحة',
    'res': 'الموارد',
    'risk': 'المخاطر',
    'drive': 'مستكشف الملفات',
    'admin': 'إعدادات النظام',
    '1.0': 'منطقة تركيز البدء',
    '1.1': 'نطاق الحوكمة',
    '1.2': 'نطاق أصحاب المصلحة',
    '2.0': 'منطقة تركيز التخطيط',
    '2.1': 'نطاق الحوكمة',
    '1.1.1': 'ميثاق المشروع',
    '1.1.2': 'سياسات وإجراءات المشروع',
    '2.1.2': 'خطة إدارة المشروع',
    '2.1.1': 'خطة إدارة التغيير',
    '2.1.3': 'خطة إدارة الجودة',
    '2.1.6': 'خطة إدارة الاتصالات',
    '2.1.7': 'خطة إدارة أصحاب المصلحة',
    '2.1.8': 'خطة إدارة المتطلبات',
    '2.1.9': 'خطة إدارة النطاق',
    '2.1.10': 'خطة إدارة الموارد البشرية',
    '2.1.11': 'خطة إدارة الجدول الزمني',
    '2.1.12': 'خطة إدارة التكاليف',
    '2.1.13': 'خطة إدارة المشتريات',
    '2.1.14': 'خطة إدارة المخاطر',
    '2.1.4': 'مقاييس الجودة',
    '2.1.5': 'سجل الافتراضات والقيود',
    '2.5': 'نطاق أصحاب المصلحة',
    '1.2.1': 'سجل أصحاب المصلحة',
    '1.2.2': 'مصفوفة تحليل أصحاب المصلحة',
    '2.2': 'نطاق النطاق',
    '2.2.3': 'بيان نطاق المشروع',
    '2.2.4': 'توثيق المتطلبات',
    '2.2.6': 'مصفوفة تتبع المتطلبات',
    '2.2.9': 'هيكل تقسيم العمل',
    '2.3': 'الجدول الزمني للمشروع',
    '2.4': 'نطاق المالية',
    '2.4.0': 'جدول الكميات',
    '2.6': 'نطاق الموارد',
    '2.6.1': 'متطلبات موارد النشاط',
    '2.6.21': 'إدارة المهام',
    '2.6.22': 'الاجتماعات والمحاضر',
    '2.6.4': 'هيكل تقسيم الموارد',
    '2.6.5': 'مصفوفة تخصيص المسؤوليات',
    '2.6.6': 'الأدوار والمسؤوليات',
    '2.6.7': 'معايير اختيار المصدر',
    '2.7': 'مركز المخاطر والفرص',
    '2.7.5': 'سجل المخاطر',
    '2.7.1': 'تقييم الاحتمالية والأثر',
    '2.7.2': 'مصفوفة الاحتمالية والأثر',
    '3.0': 'منطقة تركيز التنفيذ',
    '3.1': 'نطاق الحوكمة',
    '3.1.3': 'سجل القرارات',
    '3.1.4': 'تدقيق الجودة',
    '3.2': 'نطاق أصحاب المصلحة',
    '3.3': 'نطاق الموارد',
    '3.4': 'مركز إدارة التغيير',
    '3.3.1': 'دليل الفريق',
    '3.3.5': 'اتفاقية تشغيل الفريق',
    '3.3.2': 'تقييم أداء عضو الفريق',
    '3.3.6': 'تقييم أداء الفريق',
    '3.3.4': 'سجل الموردين الرئيسي',
    'vendor_evaluation': 'تقييم الموردين',
    'add_new_supplier': 'اضافة مورد جديد',
    'edit_supplier_profile': 'تعديل ملف المورد',
    'add_supplier': 'إضافة مورد',
    'supplier_code': 'رمز المورد',
    'legal_supplier_name': 'اسم المورد (قانوني)',
    'supplier_name': 'اسم المورد',
    'discipline': 'التخصص',
    'discipline_masterformat': 'التخصص (MASTERFORMAT)',
    'operational_status': 'حالة التشغيل',
    'register_supplier': 'تسجيل المورد',
    'update_supplier': 'تحديث المورد',
    'add_company': 'اضافة شركة جديدة',
    'edit_company': 'تعديل بيانات الشركة',
    'company_details_desc': 'أدخل تفاصيل الشركة أدناه.',
    'company_name': 'اسم الشركة',
    'company_name_placeholder': 'مثال: زريا للإنشاءات',
    'type_main': 'رئيسي (زريا)',
    'type_supplier': 'مورد',
    'type_stakeholder': 'صاحب مصلحة',
    'type_other': 'أخرى',
    'save_company': 'حفظ الشركة',
    'address': 'العنوان',
    'phone': 'رقم الهاتف',
    'website': 'الموقع الإلكتروني',
    'search_suppliers': 'البحث عن طريق اسم المورد أو الرمز أو التخصص...',
    'po_total': 'إجمالي أوامر الشراء',
    'paid': 'المدفوع',
    'balance': 'الرصيد',
    'supplier_profile': 'ملف المورد',
    'supplier_details': 'تفاصيل المورد',
    'download_statement': 'تحميل كشف الحساب الكامل',
    'no_pos_found': 'لا توجد أوامر شراء لهذا المورد.',
    'vendor_stats': 'إحصائيات المورد',
    '3.3.3': 'تقارير التقدم',
    '4.0': 'منطقة تركيز المراقبة',
    '4.1': 'نطاق الحوكمة',
    '4.1.2': 'قبول المخرجات',
    '4.2': 'نطاق المالية',
    '4.2.5': 'لوحة تحكم أوامر الشراء',
    '4.2.6': 'إدارة أوامر الشراء',
    '4.2.4': 'تتبع أوامر الشراء التراكمي',
    '4.2.3': 'شهادة الدفع',
    '4.2.1': 'تقرير حالة المقاول',
    '4.2.2': 'تقرير حالة القيمة المكتسبة',
    '4.3': 'نطاق أصحاب المصلحة',
    '4.3.1': 'تقرير أداء المشروع',
    '4.3.2': 'تحليل الانحراف',
    '4.4': 'نطاق المخاطر',
    '4.4.1': 'تدقيق المخاطر',
    '5.0': 'منطقة تركيز الإغلاق',
    '5.1': 'نطاق الحوكمة',
    '5.1.1': 'سجل الدروس المستفادة',
    '5.1.2': 'إغلاق المشروع',
    '5.2': 'نطاق المالية',
    '5.2.1': 'إغلاق العقد',
    '5.2.2': 'تدقيق المشتريات',
    'admin-users': 'إدارة المستخدمين',
    'admin-projects': 'إدارة المشاريع',
    'admin-companies': 'دليل الشركات',
    'admin-contacts': 'دليل جهات الاتصال',
    'domain_docs_forms': 'وثائق ونماذج النطاق',
    'project_logs': 'سجلات المشروع',
    'initializing_zarya': 'جاري تهيئة زاريا...',
    'domain_performance': 'أداء النطاق',
    'actual': 'الفعلي',
    'no_chart_data': 'لا توجد بيانات مخطط متاحة لهذا النطاق.',
    'domain_alerts': 'تنبيهات النطاق',
    'no_active_alerts': 'لا توجد تنبيهات نشطة',
    'welcome_back': 'مرحباً بعودتك',
    'sign_in_desc': 'قم بتسجيل الدخول للوصول إلى مساحة عمل إدارة المشروع وتكامل Google Drive.',
    'secure': 'آمن',
    'sign_in_google': 'تسجيل الدخول باستخدام جوجل',
    'terms_privacy': 'بتسجيل الدخول، فإنك توافق على شروط الخدمة وسياسة الخصوصية الخاصة بنا.',
    'enterprise_security': 'أمن على مستوى المؤسسات',
    'project_management_processes': 'عمليات إدارة المشروع وقرارات التكييف',
    'process_tools_techniques': 'أدوات وتقنيات العمليات',
    'variances_baseline_management': 'إدارة الانحرافات والخطوط الأساسية',
    'project_reviews': 'مراجعات المشروع',
    'phase': 'المرحلة',
    'key_deliverables': 'المخرجات الرئيسية',
    'knowledge_area': 'مجال المعرفة',
    'processes': 'العمليات',
    'tailoring_decisions': 'قرارات التكييف',
    'tools_techniques': 'الأدوات والتقنيات',
    'scope_variance': 'انحراف النطاق',
    'schedule_variance': 'انحراف الجدول الزمني',
    'cost_variance': 'انحراف التكلفة',
    'scope_baseline_management': 'إدارة الخط الأساسي للنطاق',
    'schedule_baseline_management': 'إدارة الخط الأساسي للجدول الزمني',
    'cost_baseline_management': 'إدارة الخط الأساسي للتكلفة',
    'governance_plans': 'خطط الحوكمة',
    'plan_integration': 'تكامل الخطط',
    'plan_integration_desc': 'يتم دمج خطط الإدارة لضمان إدارة متسقة للخطوط الأساسية عبر جميع مجالات المشروع.',
    'management_plans': 'خطط الإدارة',
    'policies_procedures': 'السياسات والإجراءات',
    'schedule': 'الجدول الزمني',
    'resource_optimization_hub': 'مركز تحسين الموارد',
    'resource_plan': 'خطة الموارد',
    'resource_structure': 'هيكل الموارد',
    'responsibility_matrix': 'مصفوفة المسؤوليات',
    'job_descriptions': 'الوصف الوظيفي',
    'optimization': 'التحسين',
    'export_landscape_pdf': 'تصدير PDF بالعرض',
    'ram_raci_matrix': 'مصفوفة RAM / RACI',
    'intersection_wbs_personnel': 'تقاطع حزم عمل WBS والموظفين المعينين.',
    'responsible': 'مسؤول',
    'accountable': 'مساءل',
    'consulted': 'مستشار',
    'informed': 'مطلع',
    'accountable_requires_definition': 'المساءل (A) يتطلب تعريف دور معتمد',
    'risk_register': 'سجل المخاطر',
    'risk_assessment': 'تقييم المخاطر',
    'detailed_risk_sheets': 'أوراق المخاطر التفصيلية',
    'issue_log': 'سجل القضايا',
    'risk_audit': 'تدقيق المخاطر',
    'loading_risk_hub': 'جاري تحميل مركز المخاطر...',
    'change_management_hub': 'مركز إدارة التغيير',
    'total_change_requests': 'إجمالي طلبات التغيير',
    'approved_variations': 'التغييرات المعتمدة',
    'pending_review': 'قيد المراجعة',
    'total_cost_impact': 'إجمالي تأثير التكلفة',
    'change_request_register': 'سجل طلبات التغيير',
    'search_requests': 'البحث في الطلبات...',
    'new_request': 'طلب جديد',
    'back_to_hub': 'العودة للمركز',
    'create_request': 'إنشاء طلب',
    'request_id': 'رقم الطلب',
    'description_of_change': 'وصف التغيير',
    'justification': 'المبررات',
    'financial_impact': 'الأثر المالي',
    'time_impact_days': 'الأثر الزمني (أيام)',
    'po_number': 'رقم أمر الشراء',
    'variation_items': 'بنود التغيير',
    'net_impact': 'صافي الأثر',
    'new_contract_total': 'إجمالي العقد الجديد',
    'original_value': 'القيمة الأصلية',
    'edit_request': 'تعديل الطلب',
    'no_change_requests_found': 'لم يتم العثور على طلبات تغيير',
    'old_qty': 'الكمية السابقة',
    'new_qty': 'الكمية الجديدة',
    'in_review': 'قيد المراجعة',
    'quantity_cost': 'الكمية/التكلفة',
    'time': 'الوقت',
    'quality': 'الجودة',
    'other': 'أخرى',
    'preparer': 'المعد',
    'contractor': 'المقاول',
    'change_request_form': 'نموذج طلب التغيير',
    'dom_gov': 'نطاق الحوكمة',
    'dom_scope': 'نطاق النطاق',
    'dom_sched': 'نطاق الجدول الزمني',
    'dom_fin': 'نطاق المالية',
    'dom_stake': 'نطاق أصحاب المصلحة',
    'dom_res': 'نطاق الموارد',
    'dom_risk': 'نطاق المخاطر',
    'team_directory': 'دليل الفريق',
    'operating_agreement': 'اتفاقية التشغيل',
    'performance_assessment': 'تقييم الأداء',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRtl = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl }}>
      <div className={isRtl ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
