import React, { createContext, useContext, useState, useEffect } from 'react';
import { cn, stripNumericPrefix } from '../lib/utils';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  th: (key: string) => string;
  isRtl: boolean;
  isHelpRtl: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'boq_versions': 'BOQ Versions',
    'version_number': 'Version No.',
    'boq_revisions': 'BOQ Revisions',
    'issued_at': 'Issued At',
    'issued_by': 'Issued By',
    'create_new_version': 'Create New Version',
    'edit_version': 'Edit Version',
    'select_version': 'Select Version',
    'no_versions_found': 'No BOQ versions found',
    'import_excel': 'Import Excel',
    'import_pdf': 'Import PDF',
    'import_boq': 'Import BOQ',
    'confirm_import': 'Confirm Import',
    'back_to_versions': 'Back to Versions',
    'm3': 'Cubic Meter (m3)',
    'm2': 'Square Meter (m2)',
    'm': 'Linear Meter (m)',
    'ton': 'Ton',
    'kg': 'Kilogram (kg)',
    'LS': 'Lump Sum (LS)',
    'sum': 'Sum',
    'set': 'Set',
    'pcs': 'Pieces (pcs)',
    'trip': 'Trip',
    'hour': 'Hour',
    'day': 'Day',
    'month': 'Month',
    'job': 'Job',
    'global': 'Global',
    'lot': 'Lot',
    'list': 'List',
    'matrix': 'Matrix',
    'manage_closely': 'Manage Closely',
    'keep_satisfied': 'Keep Satisfied',
    'keep_informed': 'Keep Informed',
    'monitor': 'Monitor',
    'power': 'Power',
    'interest': 'Interest',
    'dashboard': 'Dashboard',
    'core_data': 'CORE DATA',
    'finance': 'FINANCE',
    'governance': 'GOVERNANCE',
    'utilities': 'UTILITIES',
    'project_management_plan': 'Project Management Plan',
    'resources_optimization': 'Resources & Optimization',
    'stakeholder_register': 'Stakeholder Register',
    'assumptions_log': 'Assumptions Log',
    'decision_log': 'Decision Log',
    'lessons_learned': 'Lessons Learned',
    'gantt_chart': 'Gantt Chart',
    'wbs': 'WBS',
    'boq': 'BOQ',
    'po_management': 'PO',
    'payment_certificate': 'Payment Certificate',
    'earned_value_report': 'Earned Value Report',
    'progress_reports': 'Progress Reports',
    'task_management': 'Task Management',
    'risk_opportunity_hub': 'Risk & Opportunity Hub',
    'change_management': 'Change Management',
    'meeting_management': 'Meeting Management',
    'project_files': 'Project Files',
    'settings': 'Settings',
    'admin_settings': 'Admin Settings',
    'users': 'Users',
    'contacts': 'Contacts',
    'companies': 'Companies',
    '3m_resources': '3M Resources',
    'work_packages': 'Work Packages',
    'wbs_hierarchy': 'WBS Hierarchy',
    'cost_accounts': 'Cost Accounts',
    'structure': 'Structure',
    'scheduling': 'Scheduling',
    'search_hierarchy': 'Search hierarchy...',
    'ai_generate_wbs': 'AI Generate WBS',
    'add_level': 'Add Level',
    'no_hierarchy_defined': 'No Hierarchy Defined',
    'no_hierarchy_hint': 'Start by adding major project zones or sectors to build your WBS.',
    'add_cost_account': 'Add Cost Account',
    'delete_selected': 'Delete Selected',
    'manage_cost_accounts_desc': 'Manage project-specific cost accounts and budget divisions.',
    'add_work_package': 'Add Work Package',
    'manage_work_packages_desc': 'Manage detailed work packages linked to WBS levels and Cost Accounts.',
    'projects': 'Projects',
    'search_pages': 'Search pages...',
    'search_results': 'Search Results',
    'favorites': 'Favorites',
    'add_to_favorites': 'Add to Favorites',
    'in_favorites': 'In Favorites',
    'quick_access_favorites': 'Quick Access Favorites',
    'archive': 'Archive',
    'new_meeting': 'New Meeting',
    'no_meetings_found': 'No meetings found',
    'adjust_filters_hint': 'Adjust your filters or search terms to find what you\'re looking for.',
    'try_searching_hint': 'Try searching for domains like "Finance" or "Schedule"',
    'risk_management': 'Risk Management',
    'technical_review': 'Technical Review',
    'owner_meeting': 'Owner Meeting',
    'general': 'General',
    'kick_off': 'Kick-off',
    'no_notes_provided': 'No summary notes provided for this meeting.',
    'no_favorites': 'No favorites yet',
    'star_pages_to_add': 'Star pages to add them here',
    'invalid_session_or_no_version': 'Invalid import session or no version selected',
    'select_version_first': 'Please select or create a BOQ version before importing.',
    'no_results_found': 'No results found',
    'search_pmis': 'Search PMIS...',
    'welcome_back_zarya': 'Welcome to Zarya PMIS',
    'pmo_system_infrastructure': 'PMO System & Infrastructure',
    'select_organization': 'Select Organization',
    'select_active_project': 'Select Active Project',
    'contact_manager_for_access': 'Contact System Administrator for Access',
    'analyzing_available_assets': 'Analyzing Available Assets...',
    'hierarchy': 'HIERARCHY',
    'domains': 'DOMAINS',
    'select_project_files': 'Select a project to view files.',
    'loading': 'Loading...',
    'sign_out': 'Sign Out',
    'language': 'Language',
    'toggle_language': 'Toggle Language',
    'english': 'English',
    'arabic': 'العربية',
    'project_schedule': 'Project Schedule',
    'overall_progress': 'Overall Progress',
    'planned_cost': 'Planned Cost',
    'actual_cost': 'Actual Cost',
    'po_lines': 'PO Lines',
    'subcontractor_advances': 'Subcontractor Advances',
    'daily_reports': 'Daily Reports',
    'meetings': 'Meetings',
    'activities': 'Activities',
    'planned': 'Planned',
    'actual_on_time': 'Actual (On Time)',
    'actual_delayed': 'Actual (Delayed)',
    'activity_wbs': 'Activity / WBS',
    'start': 'Start',
    'finish': 'Finish',
    'duration': 'Duration',
    'progress': 'Progress',
    'today': 'Today',
    'expand_all': 'Expand All',
    'collapse_all': 'Collapse All',
    'add_activity': 'Add Activity',
    'columns': 'Columns',
    'print': 'Print',
    'generated': 'Generated',
    'project': 'Project',
    'select_project': 'Select Project',
    'no_projects_found': 'No projects found',
    'currency': 'Currency',
    'select_display_currency': 'Select Display Currency',
    'exchange_rate': 'Exchange Rate',
    'fetch_market_rate': 'Fetch market rate',
    'update_rate': 'Update Rate',
    'signed_in_as': 'Signed in as',
    'my_profile': 'My Profile',
    'cost_account': 'Cost Account',
    'grand_total': 'Grand Total',
    'total': 'Total',
    'execution': 'Execution',
    'configuration': 'Configuration',
    'view_gantt': 'Project Schedule',
    'view_activities': 'Activity List',
    'view_milestones': 'Milestones',
    'setup_plan': 'Management Plan',
    'manage_daily_progress_logs': 'Manage and track daily construction site progress logs.',
    'search_reports': 'Search reports...',
    'new_report': 'New Daily Report',
    'meeting_minutes': 'Meeting Minutes',
    'view_meeting': 'View Meeting',
    'attendees': 'Attendees',
    'agenda': 'Agenda',
    'decisions': 'Decisions',
    'incidents': 'Incidents',
    'site_weather': 'Site Weather',
    'manpower_log': 'Manpower Log',
    'equipment_log': 'Equipment Log',
    'purchase_orders': 'Purchase Orders',
    'zone': 'Zone',
    'area': 'Area',
    'building': 'Building',
    'meetings_desc': 'The institutional memory of the project.',
    'search_meetings_placeholder': 'Search by keyword (e.g. \"HVAC\", \"Concrete\")...',
    'timeline': 'Timeline',
    'meeting_health': 'Meeting Health',
    'status': 'Status',
    'progress_summary': 'Progress Summary',
    'manpower': 'Manpower',
    'equipment': 'Equipment',
    'weather': 'Weather',
    'author': 'Author',
    'incident_summary': 'Incident Summary',
    'staff': 'Staff',
    'draft': 'Draft',
    'submitted': 'Submitted',
    'approved': 'Approved',
    'units': 'Units',
    'description': 'Description',
    'search_activities': 'Search activities or WBS...',
    'project_purpose': 'Project Purpose',
    'measurable_project_objectives': 'Measurable Project Objectives',
    'high_level_project_description': 'High-Level Project Description',
    'high_level_deliverables': 'High-Level Deliverables',
    'overall_project_risk': 'Overall Project Risk',
    'summary_milestone_schedule': 'Summary Milestone Schedule',
    'preapproved_financial_resources': 'Preapproved Financial Resources',
    'budget_description': 'Budget Description/Notes',
    'project_approval_requirements': 'Project Approval Requirements',
    'project_exit_criteria': 'Project Exit Criteria',
    'assumption_log': 'Assumption Log',
    'assumption': 'Assumption',
    'constraint': 'Constraint',
    'impact_level': 'Impact Level',
    'owner': 'Owner',
    'date_identified': 'Date Identified',
    'last_validated': 'Last Validated',
    'open': 'Open',
    'closed': 'Closed',
    'updated': 'Updated',
    'high_level': 'High-Level',
    'low_level': 'Low-Level',
    'description_placeholder': 'Detail the project logic or external restriction...',
    'search_placeholder': 'Search log entries...',
    'add_entry': 'Add Log Entry',
    'select_owner': 'Select Owner...',
    'no_entries_found': 'No entries recorded in current project.',
    'confirm_delete': 'Are you sure you want to delete this entry?',
    'entry_deleted': 'Entry deleted successfully',
    'entry_updated': 'Entry updated successfully',
    'entry_created': 'Entry created successfully',
    'please_fill_required_fields': 'Please fill all required fields.',
    'position': 'Position',
    'organization': 'Organization',
    'contact_details': 'Contact Details',
    'internal_external': 'Internal / External',
    'influence_direction': 'Direction of Influence',
    'major_requirements': 'Major Requirements',
    'expectations': 'Expectations',
    'engagement_level': 'Engagement Level',
    'current_engagement': 'Current Engagement',
    'desired_engagement': 'Desired Engagement',
    'unaware': 'Unaware',
    'resistant': 'Resistant',
    'neutral': 'Neutral',
    'supportive': 'Supportive',
    'leading': 'Leading',
    'upward': 'Upward',
    'downward': 'Downward',
    'outward': 'Outward',
    'sideward': 'Sideward',
    'open_log': 'Open Detailed Log',
    'high_level_assumptions_summary': 'Summary of high-level assumptions and constraints...',
    'view_detailed_log': 'View Detailed Log',
    'impact': 'Impact',
    'critical': 'Critical',
    'back_to_list': 'Back to List',
    'project_canvas_hub': 'Project Canvas Hub',
    'interactive_workspace': 'Interactive Workspace',
    'smart_integration_active': 'Smart Integration Active',
    'core_objectives': 'CORE OBJECTIVES',
    'objectives_desc': 'Primary Project Objectives...',
    'project_boundaries': 'Project Boundaries',
    'boundaries_desc': 'What\'s included and excluded?',
    'quality_assurance': 'Quality Assurance',
    'success_criteria_desc': 'How is project success measured?',
    'matrix_structure_raci': 'Matrix Structure: RACI Logic',
    'add_node': 'Add Node',
    'role_entity': 'Role / Entity',
    'responsibility': 'Responsibility',
    'accountability': 'Accountability',
    'principal_role': 'Principal Role',
    'assigned_to': 'Assigned To',
    'repopulate_from_db': 'Repopulate from Project Database',
    'financial_framework': 'Financial Framework',
    'budget_estimate_iqd': 'High-Level Budget Estimate (IQD)',
    'budget_authority_details': 'Budget Authority Details',
    'budget_limits_desc': 'Define budget limits and approval steps.',
    'formal_approvals': 'Formal Approvals',
    'print_name': 'Print Name',
    'generate_final_charter': 'Generate Final Charter',
    'auto_populate_desc': 'Auto-populates data to PMBOK Standard PDF',
    'quarter': 'Quarter',
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'add': 'Add',
    'actions': 'Actions',
    'name': 'Name',
    'email': 'Email',
    'role': 'Role',
    'date': 'Date',
    'type': 'Type',
    'priority': 'Priority',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'active': 'Active',
    'inactive': 'Inactive',
    'completed': 'Completed',
    'in_progress': 'In Progress',
    'pending': 'Pending',
    'on_hold': 'On Hold',
    'cancelled': 'Cancelled',
    'yes': 'Yes',
    'no': 'No',
    'back': 'Back',
    'next': 'Next',
    'submit': 'Submit',
    'update': 'Update',
    'create': 'Create',
    'search': 'Search',
    'filter': 'Filter',
    'clear': 'Clear',
    'all': 'All',
    'none': 'None',
    'management': 'Management',
    'reporting': 'Reporting',
    'boq_manager': 'BOQ Manager',
    'export_reports': 'Export Reports',
    'import_data': 'Import Data',
    'completion': 'Completion %',
    'master_boq': 'Master Bill of Quantities',
    'search_items_placeholder': 'Search items...',
    'add_item': 'Add Item',
    'importing': 'Importing...',
    'qty': 'Qty',
    'unit_rate': 'Unit Rate',
    'wbs_required': 'WBS Structure Required',
    'wbs_required_hint': 'You must define your Work Breakdown Structure (WBS) before managing the Bill of Quantities.',
    'go_to_wbs': 'Go to WBS Setup',
    'project_summary': 'PROJECT SUMMARY',
    'nodes': 'NODES',
    'floor': 'Floor',
    'division': 'Division',
    'unit': 'Unit',
    'details': 'Details',
    'overview': 'Overview',
    'history': 'History',
    'comments': 'Comments',
    'attachments': 'Attachments',
    'notifications': 'Notifications',
    'profile': 'Profile',
    'logout': 'Logout',
    'login': 'Login',
    'register': 'Register',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'forgot_password': 'Forgot Password?',
    'reset_password': 'Reset Password',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'confirm_action': 'Are you sure you want to perform this action?',
    'no_data': 'No data available',
    'required_field': 'This field is required',
    'invalid_email': 'Invalid email address',
    'password_mismatch': 'Passwords do not match',
    'save_success': 'Saved successfully',
    'added_to_favorites': 'Added to favorites',
    'removed_from_favorites': 'Removed from favorites',
    'delete_success': 'Deleted successfully',
    'update_success': 'Updated successfully',
    'error_message': 'Something went wrong. Please try again.',
    'boq_value_by_location': 'BOQ Value by Location',
    'view_all_boq': 'View All BOQ',
    'project_schedule_summary': 'Project Schedule Summary',
    'view_full_schedule': 'View Full Schedule',
    'view_details': 'View Details',
    'no_sub_domains_found': 'No sub-domains found for this area.',
    'project_identity': 'Project Identity',
    'objectives_milestones': 'Objectives & Milestones',
    'financials_stakeholders': 'Financials & Stakeholders',
    'governance_approvals': 'Governance & Approvals',
    'project_title': 'Project Title',
    'date_prepared': 'Date Prepared',
    'project_sponsor': 'Project Sponsor',
    'project_manager': 'Project Manager',
    'project_customer': 'Project Customer',
    'project_purpose_justification': 'Project Purpose or Justification',
    'project_description': 'Project Description',
    'high_level_requirements': 'High-Level Requirements',
    'high_level_risks': 'High-Level Risks',
    'project_objectives': 'Project Objectives',
    'success_criteria': 'Success Criteria',
    'person_approving': 'Person Approving',
    'summary_milestones': 'Summary Milestones',
    'milestone_description': 'Milestone description...',
    'due_date': 'Due Date',
    'estimated_budget': 'Estimated Budget',
    'staffing_decisions': 'Staffing Decisions',
    'budget_management_variance': 'Budget Management and Variance',
    'technical_decisions': 'Technical Decisions',
    'conflict_resolution': 'Conflict Resolution',
    'approvals': 'Approvals',
    'pm_signature': 'Project Manager Signature',
    'sponsor_signature': 'Sponsor or Originator Signature',
    'pm_name': 'Project Manager Name',
    'sponsor_name': 'Sponsor or Originator Name',
    'download_pdf': 'Download PDF',
    'save_new_version': 'Save New Version',
    'overwrite': 'Overwrite',
    'charter_updated_success': 'Charter updated successfully.',
    'milestone': 'Milestone',
    'stakeholder': 'Stakeholder',
    'high_level_risks_placeholder': 'Enter one risk per line...',
    'charter_version_history': 'Charter Version History',
    'no_history_recorded': 'No history recorded.',
    'restore': 'Restore',
    'restricted_data_link': 'Restricted Data Link',
    'pull_from_policies': 'Pull from Policies',
    'formatted': 'Formatted',
    'rate': 'Rate',
    'initialize_project': 'Initialize Project',
    'save_changes': 'Save Changes',
    'identity_identification': 'Identity & Identification',
    'project_code': 'Project Code',
    'project_location': 'Project Location',
    'admin_pin': 'Admin PIN',
    'admin_pin_hint': 'Used for authorizing critical plan overwrites.',
    'timeline_status': 'Timeline & Status',
    'start_date': 'Start Date',
    'end_date_est': 'End Date (Est.)',
    'drive_integration': 'Drive Integration',
    'drive_integration_hint': 'When you initialize this project, PMIS will automatically create a secure folder structure in Google Drive and generate the initial Project Charter PDF based on these details.',
    'project_name_code_required': 'Project Name and Code are required.',
    'project_created_success': 'Project created successfully with Google Drive workspace!',
    'project_updated_success': 'Project information updated successfully!',
    'failed_to_save_project': 'Failed to save project',
    'seed_demo_project': 'Seed Demo Project',
    'test_drive': 'Test Drive',
    'backup_codebase': 'Backup Codebase',
    'create_new_project': 'Create New Project',
    'loading_projects': 'Loading projects...',
    'access_denied': 'Access Denied',
    'no_admin_privileges': 'You do not have administrative privileges to manage projects. Please sign in with an authorized account.',
    'return_to_dashboard': 'Return to Dashboard',
    'confirm_delete_project': 'Are you sure you want to delete this project? This will only remove it from the database.',
    'project_deleted_success': 'Project deleted from database.',
    'unassigned': 'Unassigned',
    'backing_up': 'Backing up...',
    'backup_success': 'Codebase backed up successfully to Google Drive!',
    'repairing_drive_link': 'Repairing Drive Link',
    'drive_link_repaired_success': 'Drive link and folders repaired successfully!',
    'repair_failed': 'Repair failed',
    'drive_status': 'Drive Status',
    'enterprise_structure': 'Enterprise Structure',
    'drive_diagnostics': 'Drive Diagnostics',
    'run_connection_test': 'Run Connection Test',
    'refresh_data': 'Refresh Data',
    'last_engine_error': 'Last Engine Error',
    'open_google_cloud_console': 'Open Google Cloud Console',
    'repairing_drive_link_summary': 'Re-creates the Google Drive folder structure and restores the connection for this project.',
    'connection_failed': 'Connection Failed!',
    'demo_project_added_success': 'Demo project added to database and Google Drive structure initialized!',
    'failed_to_add_demo_project': 'Failed to add demo project',
    'project_executive_dashboard': 'Project Executive Dashboard',
    'loading_project_data': 'Loading project data...',
    'no_project_selected': 'No project selected or found.',
    'select_project_hint': 'Please select a project from the header or create a new one.',
    'boq_total': 'BOQ Total',
    'quality_compliance': 'Quality Compliance',
    'strategic_performance': 'Strategic Performance',
    'view_full_report': 'View Full Report',
    'overall_completion': 'Overall Completion',
    'engineering_design': 'Engineering & Design',
    'procurement_logistics': 'Procurement & Logistics',
    'site_preparation': 'Site Preparation',
    'main_construction': 'Main Construction',
    'critical_alerts': 'Critical Alerts',
    'critical_action_required': 'Critical Action Required',
    'project_warning': 'Project Warning',
    'all_systems_operational': 'All systems operational',
    'project_activities': 'Project Activities',
    'generate_from_boq': 'Generate from BOQ',
    'add_new_work_package': 'Add New Work Package',
    'masterformat_suggestions': 'MasterFormat 16 Cost Accounts Suggestions',
    'select_division_first': 'Please select a division first.',
    'create_package': 'Create Package',
    'no_activities_found': 'No Activities Found',
    'no_activities_hint': 'Click "Add Activity" or "Generate from BOQ" to build your activity list.',
    'work_package': 'Work Package',
    'convert_to_po': 'Convert to PO',
    'assignee': 'Assignee',
    'planned_dates': 'Planned Dates',
    'activity_type': 'Activity Type',
    'confirm_delete_activity': 'Are you sure you want to delete this activity?',
    'activities_generated_success': 'Activities generated from BOQ successfully.',
    'po_created_success': 'Purchase Order created successfully.',
    'gov': 'Governance',
    'scope': 'Scope',
    'sched': 'Schedule',
    'fin': 'Finance',
    'stak': 'Stakeholders',
    'res': 'Resources',
    'risk': 'Risk',
    'drive': 'Drive Explorer',
    'admin': 'Admin Settings',
    '1.0': 'Initiating Focus Area',
    '2.0': 'Planning Focus Area',
    '3.0': 'Executing Focus Area',
    '4.0': 'Monitoring & Controlling Focus Area',
    '5.0': 'Closing Focus Area',
    '1.1.1': 'Project Charter',
    '1.1.1_summary': 'The official document that formally authorizes the project and gives the project manager the authority to use organizational resources.',
    '1.1.2': 'Business Case',
    '1.1.2_summary': 'A detailed report that outlines the economic, financial, and technical feasibility of the project, including ROI analysis.',
    '1.1.3': 'Assumption Log',
    '1.1.3_summary': 'A document that captures all assumptions and constraints identified throughout the project lifecycle.',
    '2.1.2': 'Project Management Plan',
    '2.1.2_summary': 'The primary document that defines how the project is executed, monitored, and controlled.',
    '2.1.1': 'Governance Policies',
    '2.1.1_summary': 'Official rules and procedures that govern project execution and communication protocols.',
    '2.1.13': 'Sourcing Strategy',
    '3.1.3': 'Execution QA',
    '4.1.1': 'Performance Monitoring',
    'Initiating': 'Initiating Focus Area',
    'initiating': 'Initiating',
    'Planning': 'Planning Focus Area',
    'planning': 'Planning',
    'Executing': 'Executing Focus Area',
    'executing': 'Executing',
    'Monitoring & Controlling': 'Monitoring & Controlling Focus Area',
    'monitoring': 'Monitoring & Controlling',
    'Closing': 'Closing Focus Area',
    'closing': 'Closing',
    'Governance Domain': 'Governance',
    'Stakeholders Domain': 'Stakeholders',
    'Project Charter': 'Project Charter',
    'Assumption Log': 'Assumption Log',
    'Project Policies & Procedures': 'Project Policies & Procedures',
    'Project Management Plan': 'Project Management Plan',
    'Change Management Plan': 'Change Management Plan',
    'Quality Management Plan': 'Quality Management Plan',
    'Communications Management Plan': 'Communications Management Plan',
    'Stakeholder Management Plan': 'Stakeholder Management Plan',
    'Requirements Management Plan': 'Requirements Management Plan',
    'Scope Management Plan': 'Scope Management Plan',
    'Human Resource Management Plan': 'Human Resource Management Plan',
    'Schedule Management Plan': 'Schedule Management Plan',
    'Cost Management Plan': 'Cost Management Plan',
    'Procurement Management Plan': 'Procurement Management Plan',
    'Risk Management Plan': 'Risk Management Plan',
    'Quality Metrics': 'Quality Metrics',
    'Assumption and Constraint Log': 'Assumption and Constraint Log',
    'Stakeholder Register': 'Stakeholder Register',
    'Stakeholder Analysis Matrix': 'Stakeholder Analysis Matrix',
    'Project Scope Statement': 'Project Scope Statement',
    'Requirements Documentation': 'Requirements Documentation',
    'Requirements Traceability Matrix': 'Requirements Traceability Matrix',
    'WBS Explorer': 'WBS Explorer',
    'Work Package Definitions': 'Work Package Definitions',
    'Project Schedule': 'Project Schedule',
    'BOQ': 'BOQ',
    'Develop Cost Estimates': 'Develop Cost Estimates',
    'Develop Project Budget': 'Develop Project Budget',
    'Financial Control Framework': 'Financial Control Framework',
    'Activity Resource Requirements': 'Activity Resource Requirements',
    'Task Management': 'Task Management',
    'Meetings & Minutes': 'Meetings & Minutes',
    'Resource Breakdown Structure': 'Resource Breakdown Structure',
    'Responsibility Assignment Matrix': 'Responsibility Assignment Matrix',
    'Roles and Responsibilities': 'Roles and Responsibilities',
    'Source Selection Criteria': 'Source Selection Criteria',
    'Risk & Opportunity Hub': 'Risk & Opportunity Hub',
    'Risk Register': 'Risk Register',
    'Change Requests': 'Change Requests',
    'Probability and Impact Assessment': 'Probability and Impact Assessment',
    'Probability and Impact Matrix': 'Probability and Impact Matrix',
    'Decision Log': 'Decision Log',
    'Quality Audit': 'Quality Audit',
    'Change Management Hub': 'Change Management Hub',
    'Team Directory': 'Team Directory',
    'Team Operating Agreement': 'Team Operating Agreement',
    'Team Member Performance Assessment': 'Team Member Performance Assessment',
    'Team Performance Assessment': 'Team Performance Assessment',
    'Supplier Master Register': 'Supplier Master Register',
    'Progress Reports': 'Progress Reports',
    'Deliverable Acceptance': 'Deliverable Acceptance',
    'PO Control Dashboard': 'PO Control Dashboard',
    'PO Management': 'PO Management',
    'Cumulative PO Tracking': 'Cumulative PO Tracking',
    'Payment Certificate': 'Payment Certificate',
    'Contractor Status Report': 'Contractor Status Report',
    'Earned Value Status Report': 'Earned Value Status Report',
    'Project Performance Report': 'Project Performance Report',
    'Variance Analysis': 'Variance Analysis',
    'Risk Audit': 'Risk Audit',
    'Lessons Learned Register': 'Lessons Learned Register',
    'Closure Report': 'Closure Report',
    'Contract Closure Report': 'Contract Closure Report',
    'Procurement Audit': 'Procurement Audit',
    'admin-users': 'User Management',
    'admin-projects': 'Project Management',
    'admin-companies': 'Company Directory',
    'admin-contacts': 'Contact Directory',
    'domain_docs_forms': 'Domain Documentation & Forms',
    'project_logs': 'Project Logs',
    'initializing_zarya': 'Initializing PMIS...',
    'domain_performance': 'Domain Performance',
    'actual': 'Actual',
    'no_chart_data': 'No chart data available for this domain.',
    'domain_alerts': 'Domain Alerts',
    'no_active_alerts': 'No active alerts',
    'welcome_back': 'Welcome Back',
    'sign_in_desc': 'Sign in to access your project management workspace and Google Drive integration.',
    'secure': 'Secure',
    'sign_in_google': 'Sign in with Google',
    'terms_privacy': 'By signing in, you agree to our Terms of Service and Privacy Policy.',
    'enterprise_security': 'Enterprise Grade Security',
    'project_required': 'Project Selection Required',
    'please_select_project_to_continue': 'You need to select a project to access this workspace. Please use the project selector in the top header.',
    'click_select_project_in_header': 'Open the Project Selector',
    'choose_company_and_project': 'Choose your company and active project',
    'project_management_processes': 'Project Management Processes and Tailoring Decisions',
    'process_tools_techniques': 'Process Tools and Techniques',
    'variances_baseline_management': 'Variances and Baseline Management',
    'project_reviews': 'Project Reviews',
    'phase': 'Phase',
    'key_deliverables': 'Key Deliverables',
    'knowledge_area': 'Knowledge Area',
    'processes': 'Processes',
    'tailoring_decisions': 'Tailoring Decisions',
    'tools_techniques': 'Tools and Techniques',
    'scope_variance': 'Scope Variance',
    'schedule_variance': 'Schedule Variance',
    'cost_variance': 'Cost Variance',
    'scope_baseline_management': 'Scope Baseline Management',
    'schedule_baseline_management': 'Schedule Baseline Management',
    'cost_baseline_management': 'Cost Baseline Management',
    'governance_plans': 'Governance Plans',
    'plan_integration': 'Plan Integration',
    'plan_integration_desc': 'Management plans are integrated to ensure consistent baseline management across all project domains.',
    'management_plans': 'Management Plans',
    'policies_procedures': 'Policies & Procedures',
    'schedule': 'Schedule',
    'resource_optimization_hub': 'Resources & Optimization Hub',
    'resource_plan': 'Resource Plan',
    'resource_structure': 'Resource Structure',
    'responsibility_matrix': 'Responsibility Matrix',
    'job_descriptions': 'Job Descriptions',
    'optimization': 'Optimization',
    'export_landscape_pdf': 'Export Landscape PDF',
    'ram_raci_matrix': 'RAM / RACI Matrix',
    'intersection_wbs_personnel': 'Intersection of WBS work packages and assigned personnel.',
    'responsible': 'Responsible',
    'accountable': 'Accountable',
    'consulted': 'Consulted',
    'informed': 'Informed',
    'accountable_requires_definition': 'Accountable (A) requires approved Role definition',
    'risk_register': 'Risk Register',
    'risk_assessment': 'Risk Assessment',
    'detailed_risk_sheets': 'Detailed Risk Sheets',
    'issue_log': 'Issue Log',
    'risk_audit': 'Risk Audit',
    'loading_risk_hub': 'Loading Risk Hub...',
    'change_management_hub': 'Change Management Hub',
    'total_change_requests': 'Total Change Requests',
    'approved_variations': 'Approved Variations',
    'pending_review': 'Pending Review',
    '6': 'Resources_Domain',
    '7': 'Risk_Domain',
    'total_cost_impact': 'Total Cost Impact',
    'change_request_register': 'Change Request Register',
    'new_request': 'New Request',
    'description_of_change': 'Description of Change',
    'justification': 'Justification',
    'financial_impact': 'Financial Impact',
    'time_impact_days': 'Time Impact (Days)',
    'variation_items': 'Variation Items',
    'net_impact': 'Net Impact',
    'new_contract_total': 'New Contract Total',
    'original_value': 'Original Value',
    'edit_request': 'Edit Request',
    'no_change_requests_found': 'No change requests found',
    'old_qty': 'Old Qty',
    'new_qty': 'New Qty',
    'in_review': 'In Review',
    'quantity_cost': 'Quantity/Cost',
    'time': 'Time',
    'quality': 'Quality',
    'other': 'Other',
    'preparer': 'Preparer',
    'contractor': 'Contractor',
    'change_request_form': 'CHANGE REQUEST FORM',
    'dom_gov': 'Governance Domain',
    'dom_scope': 'Scope Domain',
    'dom_sched': 'Schedule Domain',
    'dom_fin': 'Finance Domain',
    'dom_stake': 'Stakeholders Domain',
    'dom_res': 'Resources Domain',
    'dom_risk': 'Risk Domain',
    'team_directory': 'Team Directory',
    'operating_agreement': 'Operating Agreement',
  'performance_assessment': 'Performance Assessment',
    'input_arsenal': 'Input Arsenal',
    'connected_data_extract': 'Connected Data Extract',
    'approval_integration': 'Approval & Integration',
    'governance_context': 'Governance Context',
    'tools_logic': 'Tools & Logic',
    'output_tier': 'Output Tier',
    'archive_ready': 'Archive Ready',
    'digitally_verified': 'Digitally Verified',
    'cross_process_link_active': 'Cross-Process Link Active',
    'source_context': 'Source Context',
    'ready_for_formal_sign_off': 'Ready for formal sign-off & archiving',
    'refining_output_artifact': 'Refining Output Artifact',
    'view_source_process': 'View Source Process',
    'baseline': 'Baseline',
    'drive_sync': 'Drive Sync',
    'live': 'Live',
    'uploading': 'Uploading...',
    'generate_pdf': 'Generate PDF',
    'push_to_baseline': 'Push to Baseline',
    'initial_process_state': 'Initial Process State',
    'standard_processing_only': 'Standard Processing Only',
    'processing_logic': 'Processing Logic',
    'enterprise_governance_protocol': 'Enterprise Governance Protocol',
    'automated_cloud_archival_plan': 'Automated Cloud Archival Plan',
    'zarya_creates_structure': 'PMIS creates a dedicated structure for this project:',
    'enterprise_sync': 'Enterprise Sync',
    'items': 'Items',
    'export_pdf_deliverable': 'Export PDF Deliverable',
    'finalizing_resultant_artifact': 'Finalizing Resultant Artifact',
    'awaiting_work_completion': 'Awaiting work completion',
    'note_read_only': 'Note: This view is read-only to maintain "Single Source of Truth."',
    'domain': 'Domain',
    'focus_area': 'Focus Area',
    'prepared_by': 'Prepared By',
    'reviewed_by': 'Reviewed By',
    'approved_by': 'Approved By',
    'synchronizing_artifact': 'Synchronizing Artifact...',
    'pdf_saved_to_drive': 'PDF saved to Google Drive',
    'drive_upload_failed': 'Drive upload failed',
    'business_case': 'Business Case',
    'agreements': 'Agreements',
    'management_policies': 'Management Policies',
    'contract_agreements': 'Contract Agreements',
    'advance_payment_bonds': 'Advance Payment Bonds',
    'go_to_wbs_setup': 'Go to WBS Setup',
    'repopulate_from_project_db': 'Repopulate from Project Database',
    'project_management_pmis': 'Construction Management PMIS',
    'unique_record_id': 'Unique Record ID',
    'baseline_timestamp': 'Baseline Timestamp',
    'all_rights_reserved': 'All rights reserved.',
    'manage_statuses': 'Manage Statuses',
    'all_tasks': 'All Tasks',
    'my_tasks': 'My Tasks',
    'add_task': 'Add Task',
    'kanban_view': 'Kanban View',
    'list_view': 'List View',
    'assumption_constraint': 'Assumption & Constraint',
    'issues': 'Issues',
    'meeting_actions': 'Meeting Actions',
    'search_tasks': 'Search tasks...',
    'task_label': 'Task',
    'status_label': 'Status',
    'assignee_label': 'Assignee',
    'priority_label': 'Priority',
    'due_date_label': 'Due Date',
    'add_status': 'Add Status',
    'status_name_placeholder': 'Status Name...',
    'todo': 'To Do',
    'planning_status': 'Planning',
    'rfp': 'RFP',
    'tendering': 'Tendering',
    'at_risk': 'At Risk',
    'update_required': 'Update Required',
    'domain_overview_desc': 'View domain performance, KPIs, and active processes.',
    'navigation': 'Navigation',
    'enterprise_standard': 'Enterprise Standard',
    'total_processes': 'Total Processes',
    'baseline_status': 'Baseline Status',
    'view_process': 'Launch Process',
    'this_month': 'this month',
    'domain_kpi_index': 'Domain KPI Index',
    'standard_compliance': 'Standard Compliance',
    'process_lifecycle': 'Process Lifecycle',
    'no_processes': 'No processes available',
    'active_processes': 'Active Processes',
    'project_context': 'Project Context',
    'domain_kpis': 'Domain KPIs',
    'task_instructions': 'Double-click to open and edit the task, or drag and drop to change its status.',
    'initiating_summary': 'Establish project vision and official authorized start.',
    'planning_summary': 'Build the full roadmap and project baselines.',
    'executing_summary': 'Lead work activities according to the established plan.',
    'monitoring_summary': 'Track, review, and regulate progress and performance.',
    'closing_summary': 'Finalize all activities and formal project turnover.',
    'favorites_summary': 'Access your most used pages quickly.',
    'generate_pdf_summary': 'Generate a professional PDF report and save to Google Drive.',
    'push_baseline_summary': 'Update the project baseline with current data.',
    'drive_explorer_summary': 'Manage project documents in the secure cloud folder.',
    'admin_settings_summary': 'Configure users, roles, and enterprise-level settings.',
    'change_language_summary': 'Switch interface guidance between English and Arabic.',
    'search_summary': 'Quickly find any page or project record.',
    'user_profile_summary': 'Manage your personal profile and account settings.',
    'project_selector_summary': 'Switch between different projects in your portfolio.',
    'overview_summary': 'Return to the domain dashboard for a high-level performance overview.',
    'boq_manager_summary': 'Open the master Bill of Quantities to manage scope and costs.',
    'boq_summary': 'Complete list of all items and quantities for the project.',
    'export_summary': 'Generate and download professional project reports and documents.',
    'import_data_summary': 'Import BOQ items from Excel or PDF. Our AI can automatically extract details from technical documents.',
    'add_item_summary': 'Manually add a new line item to the Bill of Quantities. You can specify quantity, unit, and local rate.',
    'add_activity_summary': 'Create a new project activity. Define duration, budget, and links to the work breakdown structure.',
    'delete_selected_summary': 'Remove the marked items from the database. Warning: This action cannot be undone.',
    'search_items_summary': 'Filter the list by description, cost account, or location to find specific work packages quickly.',
    'export_reports_summary': 'Generate a professional PDF of the current Bill of Quantities, formatted for submission.',
    'generate_schedule_summary': 'Automatically generate activity list from BOQ items. Activities inherit descriptions and budgets.',
    'add_milestone_summary': 'Add a zero-duration event to track critical project checkpoints or contractual obligations.',
    'zoom_in_summary': 'Increase chart resolution to view day-by-day details.',
    'zoom_out_summary': 'Decrease resolution to see months or quarters in a single view.',
    'scroll_to_today_summary': 'Scroll the timeline to focus on the current day.',
    'column_settings_summary': 'Choose which data fields to display in the task table (e.g., Dates, SPI, Cost).',
    'governance_summary': 'Manage policies, charters, and management plans.',
    'scope_summary': 'Define requirements, WBS, and work packages.',
    'schedule_summary': 'Track timelines, activities, and Gantt charts.',
    'finance_summary': 'Control budgets, BOQs, and payments.',
    'stakeholders_summary': 'Manage registry and engagement of project parties.',
    'resources_summary': 'Optimize manpower, equipment, and materials.',
    'risk_summary': 'Identify and mitigate project uncertainties.',
    '1.3.1_sched': 'Define High-Level Timeline',
    '1.3.2_sched': 'Identify Major Activities',
    '2.3.1_sched': 'Activity Definition Table',
    '2.3.2_sched': 'Sequence Activities (Network)',
    '2.3.3_sched': 'Master Schedule (Gantt)',
    '2.3.4_sched': 'Estimate Activity Durations',
    '2.3.5_sched': 'Develop Schedule Baseline',
    '3.3.1_sched': 'Manage Schedule Execution',
    '3.3.2_sched': 'Progress Update (Gantt)',
    '3.3.3_sched': 'Daily Progress Reports',
    '4.3.1_sched': 'Monitor Schedule Performance',
    '4.3.2_sched': 'Control Schedule Changes',
    '5.3.1_sched': 'Final Schedule Validation',
    '5.3.2_sched': 'Archive Schedule Records',
    '2.4.1_summary': 'Manage the detailed Bill of Quantities, units, and rates.',
    '3.3.3_sched_summary': 'Formal daily logs of site activities.',
    '3.3.2_sched_summary': 'Monitor actual progress against the project baseline.',
    '2.3.3_sched_summary': 'Master project schedule and Gantt chart view.',
    '1.3.1_sched_summary': 'Define high-level roadmap and major project milestones.',
    '1.3.2_sched_summary': 'Decompose core deliverables into primary activities.',
    '2.3.1_sched_summary': 'Granular breakdown of project work into trackable activities.',
    '2.3.2_sched_summary': 'Link activities and establish logical progression.',
    '2.3.4_sched_summary': 'Determine time required for each activity.',
    '2.3.5_sched_summary': 'Establish the formal Project Schedule and Baseline.',
    '3.3.1_sched_summary': 'Coordinate team actions and track daily progress.',
    '4.3.1_sched_summary': 'Analyze schedule variance and utilize EVM.',
    '4.3.2_sched_summary': 'Manage modifications to the schedule baseline.',
    '5.3.1_sched_summary': 'Obtain stakeholder acceptance for final performance.',
    '5.3.2_sched_summary': 'Consolidate and archive all schedule artifacts.',
    '3.6.4_summary': 'Log meeting minutes, agendas, and decisions.',
    '3.6.3_summary': 'Interactive task board for team collaboration.',
    '2.7.5_summary': 'Registry of project risks, impacts, and responses.',
    '3.1.3_summary': 'Formal record of project decisions and authorizations.',
    'daily-reports_summary': 'Daily site construction logs and activity tracking.',
    '2.7.6': 'Risk Report',
    '2.1.14': 'Risk Management Plan',
    '2.1.15': 'Sourcing Strategy Plan',
    '2.2.0': 'Scope Baseline',
    '2.4.5': 'Project Funding Requirements',
    '2.6.8': 'Team Charter',
    'foundation_center': 'Foundation Center',
    'foundation_center_desc': 'Project foundational data and master data hub to control all system pages.',
    'save_master_data': 'Save Master Data',
    'business_docs': 'Business Documents',
    'business_docs_desc': 'Strategic and economic justifications for the project.',
    'feasibility_study_title': 'Feasibility Study',
    'expected_roi': 'Expected ROI',
    'benefits_plan_title': 'Benefits Management Plan',
    'strategic_benefits': 'Strategic Benefits',
    'benefit_metrics': 'Benefit Metrics',
    'realization_period': 'Realization Period',
    'contractual_obligations': 'Contractual Obligations',
    'add_agreement': 'Add Agreement/Contract',
    'no_agreements_added': 'No agreements added yet.',
    'templates_library': 'Templates Library',
    'knowledge_base': 'Knowledge Base',
    'foundation_versions': 'Foundation Data Versions',
    'master_data': 'Master Data',
    'design_hub': 'Design & Engineering',
    'design_hub_desc': 'Central repository for AutoCAD drawings, 3D models, and engineering specifications.',
    'upload_dwg': 'Upload AutoCAD (.dwg)',
    'upload_3d': 'Upload 3D Model',
    'blueprints': 'Blueprints',
    '3d_renderings': '3D Renderings',
    'technical_specs': 'Technical Specs',
    'add_design_file': 'Add Design File',
    'no_designs_found': 'No design files uploaded yet.',
    'design_version': 'Design Version',
    'cad_viewer': 'CAD Viewer',
    'view_3d': 'View 3D Model',
    'benefits_realization': 'Benefits Realization',
    'foundation_insights': 'Foundation Insights',
    'eefs': 'EEFs',
    'opas': 'OPAs',
  },
  ar: {
    'boq_versions': 'إصدارات جدول الكميات',
    'version_number': 'رقم الإصدار',
    'boq_revisions': 'مراجعات جدول الكميات',
    'issued_at': 'تاريخ الإصدار',
    'issued_by': 'صدر بواسطة',
    'create_new_version': 'إنشاء إصدار جديد',
    'edit_version': 'تعديل الإصدار',
    'select_version': 'اختر الإصدار',
    'no_versions_found': 'لا توجد إصدارات لجدول الكميات',
    'import_excel': 'استيراد Excel',
    'import_pdf': 'استيراد PDF',
    'import_boq': 'استيراد جدول الكميات',
    'confirm_import': 'تأكيد الاستيراد',
    'back_to_versions': 'العودة للإصدارات',
    'm3': 'متر مكعب (م3)',
    'm2': 'متر مربع (م2)',
    'm': 'متر طولي (م)',
    'ton': 'طن',
    'kg': 'كيلوغرام (كغم)',
    'LS': 'مبلغ مقطوع (LS)',
    'sum': 'مجموع',
    'set': 'طقم',
    'pcs': 'قطعة',
    'trip': 'نقلة',
    'hour': 'ساعة',
    'day': 'يوم',
    'month': 'شهر',
    'job': 'عملية',
    'global': 'إجمالي',
    'lot': 'مجموعة',
    'list': 'قائمة',
    'matrix': 'مصفوفة',
    'manage_closely': 'المتابعة اللصيقة',
    'keep_satisfied': 'الحفاظ على الرضا',
    'keep_informed': 'الحفاظ على الاطلاع',
    'monitor': 'المراقبة',
    'power': 'القوة / النفوذ',
    'interest': 'الاهتمام',
    'task_instructions': 'اضغط ضغطاً مزدوجاً لفتح المهمة وتعديلها، أو اسحبها وأسقطها لتغيير حالتها.',
    'initiating_summary': 'العمليات التي تتم لبدء مشروع جديد أو مرحلة جديدة من خلال الحصول على التفويض اللازم.',
    'planning_summary': 'تطوير خطة إدارة المشروع والمستندات اللازمة لتوجيه تنفيذ المشروع ومراقبته.',
    'executing_summary': 'إنجاز العمل المحدد في خطة إدارة المشروع لتحقيق أهداف المشروع.',
    'monitoring_summary': 'تتبع ومراجعة وتنظيم سير العمل والأداء في المشروع، وتحديد أي تغييرات لازمة.',
    'closing_summary': 'إنجاز جميع العمليات رسمياً لإغلاق المشروع أو المرحلة بشكل نهائي.',
    'favorites_summary': 'الوصول السريع إلى الصفحات الأكثر استخداماً.',
    'generate_pdf_summary': 'إصدار تقرير PDF احترافي وحفظه في جوجل درايف.',
    'push_baseline_summary': 'تحديث خط الأساس للمشروع بالبيانات الحالية.',
    'drive_explorer_summary': 'إدارة مستندات المشروع في المجلد السحابي الآمن.',
    'admin_settings_summary': 'تكوين المستخدمين والأدوار وإعدادات المؤسسة.',
    'change_language_summary': 'تبديل لغة التعليمات بين الإنجليزية والعربية.',
    'search_summary': 'البحث السريع عن أي صفحة أو سجل في المشروع.',
    'user_profile_summary': 'إدارة ملفك الشخصي وإعدادات الحساب.',
    'project_selector_summary': 'التنقل بين المشاريع المختلفة في محفظة أعمالك.',
    'governance_summary': 'نظام الرقابة والتوجيه الذي يضمن تحقيق أهداف المشروع والالتزام بالمعايير التنظيمية.',
    'scope_summary': 'تحديد المتطلبات، هيكل تقسيم العمل، وحزم العمل.',
    'schedule_summary': 'تتبع الجداول الزمنية والأنشطة ومخططات غانت.',
    'finance_summary': 'التحكم في الميزانيات وجداول الكميات والمدفوعات.',
    'stakeholders_summary': 'إدارة سجل ومشاركة أطراف المشروع.',
    'resources_summary': 'تحسين القوى العاملة والمعدات والمواد.',
    'risk_summary': 'تحديد وتخفيف حالات عدم اليقين في المشروع.',
    'boq': 'جدول الكميات',
    'po_management': 'PO',
    'payment_certificate': 'شهادة الدفع',
    'earned_value_report': 'تقرير القيمة المكتسبة',
    'progress_reports': 'تقارير التقدم',
    'task_management': 'إدارة المهام',
    'risk_opportunity_hub': 'مركز المخاطر والفرص',
    'change_management': 'إدارة التغيير',
    'meeting_management': 'إدارة الاجتماعات',
    'project_files': 'ملفات المشروع',
    'settings': 'الإعدادات',
    'admin_settings': 'إعدادات المسؤول',
    'users': 'المستخدمين',
    'contacts': 'جهات الاتصال',
    'companies': 'الشركات',
    '3m_resources': 'موارد 3M',
    'work_packages': 'حزم العمل',
    'wbs_hierarchy': 'الهيكل الهرمي للمشروع',
    'cost_accounts': 'حسابات التكلفة',
    'structure': 'الهيكل',
    'scheduling': 'الجدولة',
    'search_hierarchy': 'البحث في التسلسل الهرمي...',
    'ai_generate_wbs': 'توليد هيكل العمل بالذكاء الاصطناعي',
    'add_level': 'إضافة مستوى',
    'no_hierarchy_defined': 'لم يتم تعريف تسلسل هرمي',
    'no_hierarchy_hint': 'ابدأ بإضافة مناطق أو قطاعات المشروع الرئيسية لبناء هيكل تقسيم العمل الخاص بك.',
    'add_cost_account': 'إضافة حساب تكلفة',
    'delete_selected': 'حذف المحدد',
    'manage_cost_accounts_desc': 'إدارة حسابات التكلفة وأقسام الميزانية الخاصة بالمشروع.',
    'add_work_package': 'إضافة حزمة عمل',
    'manage_work_packages_desc': 'إدارة حزم العمل التفصيلية المرتبطة بمستويات هيكل تقسيم العمل وحسابات التكلفة.',
    'projects': 'المشاريع',
    'search_pages': 'البحث في الصفحات...',
    'search_results': 'نتائج البحث',
    'favorites': 'المفضلة',
    'add_to_favorites': 'إضافة إلى المفضلات',
    'in_favorites': 'في المفضلات',
    'quick_access_favorites': 'الوصول السريع للمفضلة',
    'archive': 'أرشيف',
    'new_meeting': 'اجتماع جديد',
    'no_meetings_found': 'لم يتم العثور على اجتماعات',
    'adjust_filters_hint': 'قم بتعديل المرشحات أو مصطلحات البحث للعثور على ما تبحث عنه.',
    'try_searching_hint': 'حاول البحث عن مجالات مثل "المالية" أو "الجدول الزمني"',
    'risk_management': 'إدارة المخاطر',
    'technical_review': 'مراجعة فنية',
    'owner_meeting': 'اجتماع المالك',
    'general': 'عام',
    'kick_off': 'انطلاق المشروع',
    'no_notes_provided': 'لم يتم تقديم ملاحظات ملخصة لهذا الاجتماع.',
    'no_favorites': 'لا توجد صفحات مفضلة بعد',
    'star_pages_to_add': 'اضف نجمة للصفحات لتظهر هنا',
    'invalid_session_or_no_version': 'جلسة استيراد غير صالحة أو لم يتم اختيار نسخة',
    'select_version_first': 'يرجى اختيار أو إنشاء نسخة جدول كميات قبل الاستيراد.',
    'no_results_found': 'لم يتم العثور على نتائج',
    'search_pmis': 'البحث في النظام...',
    'welcome_back_zarya': 'مرحباً بكم في زاريا PMIS',
    'pmo_system_infrastructure': 'نظام ومؤسسة مكتب إدارة المشاريع',
    'select_organization': 'اختر المؤسسة',
    'select_active_project': 'اختر المشروع النشط',
    'contact_manager_for_access': 'اتصل بمسؤول النظام للحصول على صلاحية الوصول',
    'analyzing_available_assets': 'جاري تحليل الأصول المتاحة...',
    'hierarchy': 'التسلسل الهرمي',
    'domains': 'المجالات',
    'select_project_files': 'اختر مشروعاً لعرض الملفات.',
    'loading': 'جاري التحميل...',
    'sign_out': 'تسجيل الخروج',
    'language': 'اللغة',
    'toggle_language': 'تغيير اللغة',
    'english': 'English',
    'arabic': 'العربية',
    'project_schedule': 'الجدول الزمني للمشروع',
    'overall_progress': 'التقدم الإجمالي',
    'planned_cost': 'التكلفة المخططة',
    'actual_cost': 'التكلفة الفعلية',
    'po_lines': 'بنود أمر الشراء',
    'subcontractor_advances': 'سلف مقاولي الباطن',
    'daily_reports': 'التقارير اليومية',
    'meetings': 'الاجتماعات',
    'activities': 'الأنشطة',
    'planned': 'مخطط',
    'actual_on_time': 'فعلي (في الوقت)',
    'actual_delayed': 'فعلي (متأخر)',
    'activity_wbs': 'النشاط / هيكل تقسيم العمل',
    'start': 'البداية',
    'finish': 'النهاية',
    'duration': 'المدة',
    'progress': 'التقدم',
    'today': 'اليوم',
    'expand_all': 'توسيع الكل',
    'collapse_all': 'طي الكل',
    'add_activity': 'إضافة نشاط',
    'columns': 'الأعمدة',
    'print': 'طباعة',
    'generated': 'تم الإنشاء في',
    'project': 'المشروع',
    'select_project': 'اختر مشروعاً',
    'no_projects_found': 'لم يتم العثور على مشاريع',
    'currency': 'العملة',
    'select_display_currency': 'اختر عملة العرض',
    'exchange_rate': 'سعر الصرف',
    'fetch_market_rate': 'جلب سعر السوق',
    'update_rate': 'تحديث السعر',
    'signed_in_as': 'تم تسجيل الدخول باسم',
    'my_profile': 'ملفي الشخصي',
    'cost_account': 'حساب التكلفة',
    'grand_total': 'الإجمالي الكلي',
    'total': 'الإجمالي',
    'execution': 'التنفيذ',
    'configuration': 'الإعدادات',
    'view_gantt': 'الجدول الزمني للمشروع',
    'view_activities': 'قائمة الأنشطة',
    'view_milestones': 'المعالم الرئيسية',
    'setup_plan': 'خطة الإدارة',
    'manage_daily_progress_logs': 'إدارة وتتبع سجلات التقدم اليومية في موقع العمل.',
    'search_reports': 'البحث في التقارير...',
    'new_report': 'تقرير يومي جديد',
    'meeting_minutes': 'محاضر الاجتماعات',
    'view_meeting': 'عرض الاجتماع',
    'attendees': 'الحاضرون',
    'agenda': 'جدول الأعمال',
    'decisions': 'القرارات',
    'incidents': 'الحوادث',
    'site_weather': 'حالة الطقس في الموقع',
    'manpower_log': 'سجل القوى العاملة',
    'equipment_log': 'سجل المعدات',
    'purchase_orders': 'أوامر الشراء',
    'zone': 'زون / قطاع',
    'area': 'منطقة',
    'building': 'مبنى',
    'meetings_desc': 'الذاكرة المؤسسية للمشروع.',
    'search_meetings_placeholder': 'البحث بالكلمات المفتاحية (مثلاً: "تكييف"، "خرسانة")...',
    'timeline': 'الخط الزمني',
    'meeting_health': 'صحة الاجتماع',
    'status': 'الحالة',
    'progress_summary': 'ملخص التقدم',
    'manpower': 'القوى العاملة',
    'equipment': 'المعدات',
    'weather': 'الطقس',
    'author': 'المؤلف',
    'incident_summary': 'ملخص الحوادث',
    'staff': 'موظف',
    'draft': 'مسودة',
    'submitted': 'تم الإرسال',
    'approved': 'معتمد',
    'units': 'وحدة',
    'description': 'الوصف',
    'search_activities': 'البحث في الأنشطة...',
    'project_purpose': 'الغرض من المشروع',
    'measurable_project_objectives': 'أهداف المشروع القابلة للقياس ومعايير النجاح',
    'high_level_project_description': 'وصف عالي المستوى للمشروع',
    'high_level_deliverables': 'التسليمات الرئيسية',
    'overall_project_risk': 'المخاطر الكلية للمشروع',
    'summary_milestone_schedule': 'الجدول الزمني التلخيصي للمعالم',
    'preapproved_financial_resources': 'الموارد المالية المعتمدة مسبقاً',
    'budget_description': 'وصف الميزانية / ملاحظات',
    'project_approval_requirements': 'متطلبات اعتماد المشروع',
    'project_exit_criteria': 'معايير الخروج من المشروع',
    'assumption_log': 'سجل الافتراضات والقيود',
    'assumption': 'افتراض',
    'constraint': 'قيد',
    'impact_level': 'مستوى التأثير',
    'owner': 'المالك',
    'date_identified': 'تاريخ التحديد',
    'last_validated': 'آخر تحقق',
    'open': 'مفتوح',
    'closed': 'مغلق',
    'updated': 'محدث',
    'high_level': 'عالي المستوى',
    'low_level': 'منخفض المستوى',
    'description_placeholder': 'تفصيل منطق المشروع أو القيود الخارجية...',
    'search_placeholder': 'البحث في السجلات...',
    'add_entry': 'إضافة قيد للسجل',
    'select_owner': 'اختر المسئول...',
    'no_entries_found': 'لم يتم تسجيل قيود في المشروع الحالي.',
    'confirm_delete': 'هل أنت متأكد من حذف هذا القيد؟',
    'entry_deleted': 'تم حذف القيد بنجاح',
    'entry_updated': 'تم تحديث القيد بنجاح',
    'entry_created': 'تم إنشاء القيد بنجاح',
    'please_fill_required_fields': 'يرجى ملء جميع الحقول المطلوبة.',
    'stakeholder_register': 'سجل المعنيين',
    'position': 'المنصب',
    'organization': 'المؤسسة/الجهة',
    'contact_details': 'تفاصيل الاتصال',
    'internal_external': 'داخلي / خارجي',
    'influence_direction': 'اتجاه التأثير',
    'major_requirements': 'المتطلبات الرئيسية',
    'expectations': 'التوقعات',
    'engagement_level': 'مستوى المشاركة',
    'current_engagement': 'المشاركة الحالية',
    'desired_engagement': 'المشاركة المطلوبة',
    'unaware': 'غير مدرك',
    'resistant': 'مقاوم',
    'neutral': 'محايد',
    'supportive': 'داعم',
    'leading': 'قائد',
    'upward': 'إلى أعلى',
    'downward': 'إلى أسفل',
    'outward': 'للخارج',
    'sideward': 'للجانب',
    'open_log': 'افتح السجل التفصيلي',
    'view_detailed_log': 'عرض السجل التفصيلي',
    'high_level_assumptions_summary': 'ملخص الافتراضات والقيود عالية المستوى...',
    'impact': 'الأثر',
    'critical': 'حرج',
    'back_to_list': 'العودة للقائمة',
    'project_canvas_hub': 'مركز لوحة المشروع',
    'interactive_workspace': 'مساحة عمل تفاعلية',
    'smart_integration_active': 'التكامل الذكي نشط',
    'core_objectives': 'الأهداف الأساسية',
    'objectives_desc': 'أهداف المشروع الأساسية...',
    'project_boundaries': 'حدود المشروع',
    'boundaries_desc': 'ما الذي تم تضمينه واستبعاده؟',
    'quality_assurance': 'ضمان الجودة',
    'success_criteria_desc': 'كيف يتم قياس نجاح المشروع؟',
    'matrix_structure_raci': 'هيكل المصفوفة: منطق RACI',
    'add_node': 'إضافة عقدة',
    'role_entity': 'الدور / الكيان',
    'responsibility': 'المسؤولية',
    'accountability': 'المساءلة',
    'principal_role': 'الدور الرئيسي',
    'assigned_to': 'مكلف لـ',
    'repopulate_from_db': 'إعادة التعبئة من قاعدة بيانات المشروع',
    'financial_framework': 'الإطار المالي',
    'budget_estimate_iqd': 'تقدير الميزانية عالي المستوى (دينار عراقي)',
    'budget_authority_details': 'تفاصيل صلاحيات الميزانية',
    'budget_limits_desc': 'تحديد حدود الميزانية وخطوات الموافقة.',
    'formal_approvals': 'الموافقات الرسمية',
    'print_name': 'الاسم المطبوع',
    'generate_final_charter': 'إنشاء الميثاق النهائي',
    'auto_populate_desc': 'تعبئة البيانات تلقائياً في ملف PDF بمعايير PMBOK',
    'quarter': 'ربع سنة',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'edit': 'تعديل',
    'delete': 'حذف',
    'add': 'إضافة',
    'actions': 'الإجراءات',
    'name': 'الاسم',
    'email': 'البريد الإلكتروني',
    'role': 'الدور',
    'date': 'التاريخ',
    'type': 'النوع',
    'priority': 'الأولوية',
    'high': 'عالية',
    'medium': 'متوسطة',
    'low': 'منخفضة',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'completed': 'مكتمل',
    'in_progress': 'قيد التنفيذ',
    'pending': 'قيد الانتظار',
    'on_hold': 'متوقف مؤقتاً',
    'cancelled': 'ملغي',
    'yes': 'نعم',
    'no': 'لا',
    'back': 'رجوع',
    'next': 'التالي',
    'submit': 'إرسال',
    'update': 'تحديث',
    'create': 'إنشاء',
    'search': 'بحث',
    'filter': 'تصفية',
    'clear': 'مسح',
    'all': 'الكل',
    'none': 'لا شيء',
    'management': 'الإدارة',
    'reporting': 'التقارير',
    'boq_manager': 'مدير جدول الكميات',
    'export_reports': 'تصدير التقارير',
    'import_data': 'استيراد البيانات',
    'boq_summary': 'ملخص جدول الكميات',
    'completion': 'نسبة الإنجاز',
    'master_boq': 'جدول الكميات الرئيسي',
    'search_items_placeholder': 'البحث عن البنود...',
    'add_item': 'إضافة بند',
    'importing': 'جاري الاستيراد...',
    'qty': 'الكمية',
    'unit_rate': 'سعر الوحدة',
    'wbs_required': 'مطلوب هيكل تقسيم العمل',
    'wbs_required_hint': 'يجب عليك تحديد هيكل تقسيم العمل (WBS) الخاص بك قبل إدارة جدول الكميات.',
    'go_to_wbs': 'اذهب إلى إعداد WBS',
    'project_summary': 'ملخص المشروع',
    'nodes': 'عقد',
    'floor': 'طابق',
    'division': 'قسم',
    'unit': 'وحدة',
    'details': 'التفاصيل',
    'overview': 'نظرة عامة',
    'history': 'السجل',
    'comments': 'التعليقات',
    'attachments': 'المرفقات',
    'notifications': 'التنبيهات',
    'profile': 'الملف الشخصي',
    'logout': 'تسجيل الخروج',
    'login': 'تسجيل الدخول',
    'register': 'تسجيل',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'forgot_password': 'نسيت كلمة المرور؟',
    'reset_password': 'إعادة تعيين كلمة المرور',
    'error': 'خطأ',
    'success': 'نجاح',
    'warning': 'تحذير',
    'info': 'معلومات',
    'confirm_action': 'هل أنت متأكد أنك تريد القيام بهذا الإجراء؟',
    'no_data': 'لا توجد بيانات متاحة',
    'required_field': 'هذا الحقل مطلوب',
    'invalid_email': 'بريد إلكتروني غير صالح',
    'password_mismatch': 'كلمات المرور غير متطابقة',
    'save_success': 'تم الحفظ بنجاح',
    'added_to_favorites': 'تمت الإضافة إلى المفضلة',
    'removed_from_favorites': 'تمت الإزالة من المفضلة',
    'delete_success': 'تم الحذف بنجاح',
    'update_success': 'تم التحديث بنجاح',
    'error_message': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
    'boq_value_by_location': 'قيمة جدول الكميات حسب الموقع',
    'view_all_boq': 'عرض كامل جدول الكميات',
    'project_schedule_summary': 'ملخص الجدول الزمني للمشروع',
    'view_full_schedule': 'عرض الجدول الزمني الكامل',
    'view_details': 'عرض التفاصيل',
    'no_sub_domains_found': 'لم يتم العثور على مجالات فرعية لهذه المنطقة.',
    'project_identity': 'هوية المشروع',
    'objectives_milestones': 'الأهداف والمعالم',
    'financials_stakeholders': 'المالية وأصحاب المصلحة',
    'governance_approvals': 'الحوكمة والاعتمادات',
    'project_title': 'عنوان المشروع',
    'date_prepared': 'تاريخ الإعداد',
    'project_sponsor': 'راعي المشروع',
    'project_manager': 'مدير المشروع',
    'project_customer': 'عميل المشروع',
    'project_purpose_justification': 'الغرض من المشروع أو مبرراته',
    'project_description': 'وصف المشروع',
    'high_level_requirements': 'المتطلبات عالية المستوى',
    'high_level_risks': 'المخاطر عالية المستوى',
    'project_objectives': 'أهداف المشروع',
    'success_criteria': 'معايير النجاح',
    'person_approving': 'الشخص المعتمد',
    'summary_milestones': 'ملخص المعالم الرئيسية',
    'milestone_description': 'وصف المعلم...',
    'due_date': 'تاريخ الاستحقاق',
    'estimated_budget': 'الميزانية التقديرية',
    'staffing_decisions': 'قرارات التوظيف',
    'budget_management_variance': 'إدارة الميزانية والانحرافات',
    'technical_decisions': 'القرارات الفنية',
    'conflict_resolution': 'حل النزاعات',
    'approvals': 'الاعتمادات',
    'pm_signature': 'توقيع مدير المشروع',
    'sponsor_signature': 'توقيع الراعي أو المنشئ',
    'pm_name': 'اسم مدير المشروع',
    'sponsor_name': 'اسم الراعي أو المنشئ',
    'download_pdf': 'تحميل PDF',
    'save_new_version': 'حفظ نسخة جديدة',
    'overwrite': 'استبدال',
    'charter_updated_success': 'تم تحديث الميثاق بنجاح.',
    'milestone': 'معلم رئيسي',
    'stakeholder': 'صاحب مصلحة',
    'high_level_risks_placeholder': 'أدخل مخاطرة واحدة في كل سطر...',
    'charter_version_history': 'سجل نسخ الميثاق',
    'no_history_recorded': 'لم يتم تسجيل أي سجل.',
    'restore': 'استعادة',
    'restricted_data_link': 'رابط بيانات مقيد',
    'pull_from_policies': 'سحب من السياسات',
    'formatted': 'منسق',
    'rate': 'سعر',
    'initialize_project': 'تهيئة المشروع',
    'save_changes': 'حفظ التغييرات',
    'identity_identification': 'الهوية والتعريف',
    'project_code': 'رمز المشروع',
    'project_location': 'موقع المشروع',
    'admin_pin': 'رمز المسؤول (PIN)',
    'admin_pin_hint': 'يستخدم لتفويض عمليات استبدال الخطط الحرجة.',
    'timeline_status': 'الجدول الزمني والحالة',
    'start_date': 'تاريخ البدء',
    'end_date_est': 'تاريخ الانتهاء (تقديري)',
    'drive_integration': 'تكامل درايف',
    'drive_integration_hint': 'عند تهيئة هذا المشروع، سيقوم PMIS تلقائياً بإنشاء هيكل مجلد آمن في جوجل درايف وإنشاء ملف ميثاق المشروع الأولي بناءً على هذه التفاصيل.',
    'project_name_code_required': 'اسم المشروع ورمزه مطلوبان.',
    'project_created_success': 'تم إنشاء المشروع بنجاح مع مساحة عمل جوجل درايف!',
    'project_updated_success': 'تم تحديث معلومات المشروع بنجاح!',
    'failed_to_save_project': 'فشل في حفظ المشروع',
    'seed_demo_project': 'بذر مشروع تجريبي',
    'test_drive': 'اختبار درايف',
    'backup_codebase': 'نسخ احتياطي للكود',
    'create_new_project': 'إنشاء مشروع جديد',
    'loading_projects': 'جاري تحميل المشاريع...',
    'access_denied': 'تم رفض الوصول',
    'no_admin_privileges': 'ليس لديك امتيازات إدارية لإدارة المشاريع. يرجى تسجيل الدخول بحساب مخول.',
    'return_to_dashboard': 'العودة إلى لوحة القيادة',
    'confirm_delete_project': 'هل أنت متأكد أنك تريد حذف هذا المشروع؟ سيؤدي هذا فقط إلى إزالته من قاعدة البيانات.',
    'project_deleted_success': 'تم حذف المشروع من قاعدة البيانات.',
    'unassigned': 'غير معين',
    'backing_up': 'جاري النسخ الاحتياطي...',
    'backup_success': 'تم نسخ قاعدة الكود احتياطياً بنجاح إلى جوجل درايف!',
    'backup_failed': 'فشل النسخ الاحتياطي',
    'repairing_drive_link': 'إصلاح رابط Drive',
    'drive_link_repaired_success': 'تم إصلاح رابط ومجلدات Drive بنجاح!',
    'repair_failed': 'فشل الإصلاح',
    'drive_status': 'حالة Drive',
    'enterprise_structure': 'هيكل المؤسسة',
    'drive_diagnostics': 'تشخيصات Drive',
    'run_connection_test': 'تشغيل اختبار الاتصال',
    'refresh_data': 'تحديث البيانات',
    'last_engine_error': 'آخر خطأ في المحرك',
    'open_google_cloud_console': 'افتح وحدة تحكم Google Cloud',
    'repairing_drive_link_summary': 'يعيد إنشاء هيكل مجلدات Google Drive ويستعيد الاتصال لهذا المشروع.',
    'drive_connected_success': 'نجاح! تم الاتصال بجوجل درايف.',
    'connection_failed': 'فشل الاتصال!',
    'demo_project_added_success': 'تم إضافة المشروع التجريبي إلى قاعدة البيانات وتهيئة هيكل جوجل درايف!',
    'failed_to_add_demo_project': 'فشل في إضافة المشروع التجريبي',
    'project_executive_dashboard': 'لوحة القيادة التنفيذية للمشروع',
    'loading_project_data': 'جاري تحميل بيانات المشروع...',
    'no_project_selected': 'لم يتم اختيار أو العثور على أي مشروع.',
    'select_project_hint': 'يرجى اختيار مشروع من القائمة العلوية أو إنشاء مشروع جديد.',
    'boq_total': 'إجمالي جدول الكميات',
    'quality_compliance': 'الامتثال للجودة',
    'strategic_performance': 'الأداء الاستراتيجي',
    'view_full_report': 'عرض التقرير الكامل',
    'overall_completion': 'الإنجاز الكلي',
    'engineering_design': 'الهندسة والتصميم',
    'procurement_logistics': 'المشتريات والخدمات اللوجستية',
    'site_preparation': 'تجهيز الموقع',
    'main_construction': 'الإنشاءات الرئيسية',
    'critical_alerts': 'تنبيهات حرجة',
    'critical_action_required': 'مطلوب إجراء حرج',
    'project_warning': 'تحذير المشروع',
    'all_systems_operational': 'جميع الأنظمة تعمل بشكل طبيعي',
    'project_activities': 'أنشطة المشروع',
    'generate_from_boq': 'توليد من جدول الكميات',
    'add_new_work_package': 'إضافة حزمة عمل جديدة',
    'masterformat_suggestions': 'اقتراحات حسابات التكلفة MasterFormat 16',
    'select_division_first': 'يرجى اختيار قسم أولاً.',
    'create_package': 'إنشاء حزمة',
    'no_activities_found': 'لم يتم العثور على أنشطة',
    'no_activities_hint': 'انقر على "إضافة نشاط" أو "توليد من جدول الكميات" لبناء قائمة الأنشطة الخاصة بك.',
    'work_package': 'حزمة العمل',
    'convert_to_po': 'تحويل إلى أمر شراء',
    'assignee': 'المكلف',
    'planned_dates': 'التواريخ المخططة',
    'activity_type': 'نوع النشاط',
    'confirm_delete_activity': 'هل أنت متأكد أنك تريد حذف هذا النشاط؟',
    'activities_generated_success': 'تم توليد الأنشطة من جدول الكميات بنجاح.',
    'po_created_success': 'تم إنشاء أمر الشراء بنجاح.',
    'gov': 'الحوكمة',
    'scope': 'النطاق',
    'sched': 'الجدول الزمني',
    'fin': 'المالية',
    'stak': 'أصحاب المصلحة',
    'res': 'الموارد',
    'risk': 'المخاطر',
    'drive': 'مستكشف الملفات',
    'admin': 'إعدادات النظام',
    '1.0': 'منطقة تركيز البدء',
    '1.1': 'نطاق الحوكمة',
    '1.2': 'نطاق أصحاب المصلحة',
    '2.0': 'منطقة تركيز التخطيط',
    '2.1': 'نطاق الحوكمة',
    '1.1.1': 'ميثاق المشروع',
    '1.1.3': 'سجل الافتراضات',
    '1.1.2': 'دراسة الجدوى الاقتصادية',
    '2.1.2': 'خطة إدارة المشروع',
    '2.1.1': 'سياسات وإجراءات المشروع',
    '1.1.2_summary': 'تقرير مفصل يوضح الجدوى الاقتصادية والمالية والفنية للمشروع، بما في ذلك تحليل التكلفة والعائد والعائد على الاستثمار.',
    '2.1.2_summary': 'الخطة الأم التي تجمع وتكامل جميع الخطط الفرعية وتحدد كيفية تنفيذ المشروع ومراقبته وإغلاقه.',
    '2.1.1_summary': 'مجموعة القواعد واللوائح التنظيمية التي تحكم العمل في المشروع، بما في ذلك بروتوكولات التواصل والأرشفة.',
    '1.1.1_summary': 'المستند الرسمي الذي يخول المشروع ويعطي مدير المشروع الصلاحية لاستخدام موارد المؤسسة.',
    'save_button_tooltip': 'حفظ البيانات الحالية كنسخة جديدة (Baseline).',
    'update_button_tooltip': 'تحديث السجلات الحالية وحفظ التغييرات.',
    'cancel_button_tooltip': 'الرجوع إلى عرض الجدول دون حفظ التغييرات.',
    'print_button_tooltip': 'توليد ملف PDF جاهز للطباعة لهذه الوثيقة.',
    'sync_button_tooltip': 'مزامنة هذا الملف مع مجلد المشروع على Google Drive.',
    'pmp_summary': 'خطة لإدارة المشروع بما في ذلك دورة الحياة والأساسيات.',
    'business_case_summary': 'دراسة الجدوى الاقتصادية والمبررات الاستراتيجية للمشروع.',
    '2.1.3': 'خطة إدارة الجودة',
    '2.1.6': 'خطة إدارة الاتصالات',
    '2.1.7': 'خطة إدارة أصحاب المصلحة',
    '2.1.8': 'خطة إدارة المتطلبات',
    '2.1.9': 'خطة إدارة النطاق',
    '2.1.10': 'خطة إدارة الموارد البشرية',
    '2.1.11': 'خطة إدارة الجدول الزمني',
    '2.1.12': 'خطة الإدارة المالية',
    '2.1.13': 'خطة إدارة المشتريات',
    '2.1.14': 'خطة إدارة المخاطر',
    '2.1.15': 'خطة استراتيجية التوريد',
    '2.2.0': 'الخط المرجعي للنطاق',
    '2.4.5': 'متطلبات تمويل المشروع',
    '2.6.8': 'ميثاق الفريق',
    '2.7.6': 'تقرير المخاطر',
    '1.2.1_scope': 'بيان نطاق المشروع',
    '1.2.2_scope': 'وثائق المتطلبات',
    '2.4.2_fin': 'تقديرات التكاليف وأسس التقديرات',
    '2.5.1_stak': 'خطة إشراك المعنيين',
    '2.5.2_stak': 'خطة إدارة الاتصالات',
    '2.6.1_res': 'متطلبات الموارد وهيكلها (RBS)',
    '2.1.4': 'مقاييس الجودة',
    '2.1.5': 'سجل الافتراضات والقيود',
    '2.5': 'نطاق أصحاب المصلحة',
    '1.2.1': 'سجل أصحاب المصلحة',
    '1.2.2': 'مصفوفة تحليل أصحاب المصلحة',
    '2.2': 'نطاق النطاق',
    '2.2.3': 'بيان نطاق المشروع',
    '2.2.4': 'توثيق المتطلبات',
    '2.2.6': 'مصفوفة تتبع المتطلبات',
    '2.2.5': 'هيكل تقسيم العمل (WBS)',
    '2.2.7': 'تعاريف حزم العمل',
    '2.3': 'الجدول الزمني للمشروع',
    '2.4': 'نطاق المالية',
    '2.4.1': 'جدول الكميات',
    '2.4.2': 'تطوير تقديرات التكلفة',
    '2.4.3': 'تطوير ميزانية المشروع',
    '2.4.4': 'تحديد إطار الرقابة المالية',
    '2.6': 'نطاق الموارد',
    '2.6.1': 'متطلبات موارد النشاط',
    '3.6.3': 'إدارة المهام',
    '3.6.4': 'الاجتماعات والمحاضر',
    '2.6.4': 'هيكل تقسيم الموارد',
    '2.6.5': 'مصفوفة تخصيص المسؤوليات',
    '2.6.6': 'الأدوار والمسؤوليات',
    '2.6.7': 'معايير اختيار المصدر',
    '2.7': 'مركز المخاطر والفرص',
    '2.7.5': 'سجل المخاطر',
    '3.1.1': 'طلبات التغيير',
    '2.7.1': 'تقييم الاحتمالية والأثر',
    '2.7.2': 'مصفوفة الاحتمالية والأثر',
    '3.0': 'منطقة تركيز التنفيذ',
    '3.1': 'نطاق الحوكمة',
    '3.1.3': 'سجل القرارات',
    '3.1.4': 'تدقيق الجودة',
    '3.2': 'نطاق أصحاب المصلحة',
    '3.3': 'نطاق الموارد',
    '3.4': 'مركز إدارة التغيير',
    '3.3.1': 'دليل الفريق',
    '3.3.5': 'اتفاقية تشغيل الفريق',
    '3.3.2': 'تقييم أداء عضو الفريق',
    '3.3.6': 'تقييم أداء الفريق',
    '3.3.4': 'سجل الموردين الرئيسي',
    'vendor_evaluation': 'تقييم الموردين',
    'add_new_supplier': 'اضافة مورد جديد',
    'edit_supplier_profile': 'تعديل ملف المورد',
    'add_supplier': 'إضافة مورد',
    'supplier_code': 'رمز المورد',
    'legal_supplier_name': 'اسم المورد (قانوني)',
    'supplier_name': 'اسم المورد',
    'discipline': 'التخصص',
    'discipline_masterformat': 'التخصص (MASTERFORMAT)',
    'operational_status': 'حالة التشغيل',
    'register_supplier': 'تسجيل المورد',
    'update_supplier': 'تحديث المورد',
    'add_company': 'اضافة شركة جديدة',
    'edit_company': 'تعديل بيانات الشركة',
    'company_details_desc': 'أدخل تفاصيل الشركة أدناه.',
    'company_name': 'اسم الشركة',
    'company_name_placeholder': 'مثلاً: شركة PMIS للمقاولات',
    'type_main': 'رئيسي (PMIS)',
    'type_supplier': 'مورد',
    'type_stakeholder': 'صاحب مصلحة',
    'type_other': 'آخر',
    'parent_entity': 'الكيان الأم',
    'entity_type': 'نوع الكيان',
    'holding': 'مجموعة / قابضة',
    'holding_division': 'قطاع / فرع',
    'department': 'قسم / وحدة',
    'subsidiary': 'شركة تابعة',
    'vendor': 'مورد خارجي / شريك',
    'internal_entity': 'كيان داخلي تابع للمجموعة',
    'external_vendor': 'مورد خارجي',
    'no_parent': 'لا يوجد كيان أم (مستوى أعلى)',
    'move_to_parent': 'نقل إلى كيان أم',
    'is_internal_label': 'هل هي شركة داخلية تابعة للمجموعة؟',
    'save_company': 'حفظ الشركة',
    'address': 'العنوان',
    'phone': 'رقم الهاتف',
    'website': 'الموقع الإلكتروني',
    'search_suppliers': 'البحث عن طريق اسم المورد أو الرمز أو التخصص...',
    'po_total': 'إجمالي أوامر الشراء',
    'paid': 'المدفوع',
    'balance': 'الرصيد',
    'supplier_profile': 'ملف المورد',
    'supplier_details': 'تفاصيل المورد',
    'download_statement': 'تحميل كشف الحساب الكامل',
    'no_pos_found': 'لا توجد أوامر شراء لهذا المورد.',
    'vendor_stats': 'إحصائيات المورد',
    '3.3.3': 'التقارير اليومية',
    '4.0': 'منطقة تركيز المراقبة',
    '4.1': 'نطاق الحوكمة',
    '4.1.2': 'قبول المخرجات',
    '4.2': 'نطاق المالية',
    '4.2.5': 'لوحة تحكم أوامر الشراء',
    '4.2.6': 'إدارة أوامر الشراء',
    '4.2.4': 'تتبع أوامر الشراء التراكمي',
    '4.2.3': 'شهادة الدفع',
    '4.2.1': 'تقرير حالة المقاول',
    '4.2.2': 'تقرير حالة القيمة المكتسبة',
    '4.3': 'نطاق أصحاب المصلحة',
    '4.3.1': 'تقرير أداء المشروع',
    '4.3.2': 'تحليل الانحراف',
    '4.4': 'نطاق المخاطر',
    '4.4.1': 'تدقيق المخاطر',
    '5.0': 'منطقة تركيز الإغلاق',
    '5.1': 'نطاق الحوكمة',
    '5.1.1': 'سجل الدروس المستفادة',
    '5.1.2': 'إغلاق المشروع',
    '5.2': 'نطاق المالية',
    '5.2.1': 'إغلاق العقد',
    '5.2.2': 'تدقيق المشتريات',
    'admin-users': 'إدارة المستخدمين',
    'admin-projects': 'إدارة المشاريع',
    'admin-companies': 'دليل الشركات',
    'admin-contacts': 'دليل جهات الاتصال',
    'domain_docs_forms': 'وثائق ونماذج النطاق',
    'project_logs': 'سجلات المشروع',
    'initializing_zarya': 'جاري تهيئة PMIS...',
    'domain_performance': 'أداء النطاق',
    'actual': 'الفعلي',
    'no_chart_data': 'لا توجد بيانات مخطط متاحة لهذا النطاق.',
    'domain_alerts': 'تنبيهات النطاق',
    'no_active_alerts': 'لا توجد تنبيهات نشطة',
    'welcome_back': 'مرحباً بعودتك',
    'sign_in_desc': 'قم بتسجيل الدخول للوصول إلى مساحة عمل إدارة المشروع وتكامل Google Drive.',
    'secure': 'آمن',
    'sign_in_google': 'تسجيل الدخول باستخدام جوجل',
    'terms_privacy': 'بتسجيل الدخول، فإنك توافق على شروط الخدمة وسياسة الخصوصية الخاصة بنا.',
    'enterprise_security': 'أمن على مستوى المؤسسات',
    'project_required': 'مطلوب اختيار مشروع',
    'please_select_project_to_continue': 'يجب عليك اختيار مشروع للوصول إلى مساحة العمل هذه.يرجى استخدام قائمة اختيار المشاريع في الشريط العلوي.',
    'click_select_project_in_header': 'افتح قائمة اختيار المشاريع',
    'choose_company_and_project': 'اختر الشركة والمشروع النشط',
    'project_management_processes': 'عمليات إدارة المشروع وقرارات التكييف',
    'process_tools_techniques': 'أدوات وتقنيات العمليات',
    'variances_baseline_management': 'إدارة الانحرافات والخطوط الأساسية',
    'project_reviews': 'مراجعات المشروع',
    'phase': 'المرحلة',
    'key_deliverables': 'المخرجات الرئيسية',
    'knowledge_area': 'مجال المعرفة',
    'processes': 'العمليات',
    'tailoring_decisions': 'قرارات التكييف',
    'tools_techniques': 'الأدوات والتقنيات',
    'scope_variance': 'انحراف النطاق',
    'schedule_variance': 'انحراف الجدول الزمني',
    'cost_variance': 'انحراف التكلفة',
    'scope_baseline_management': 'إدارة الخط الأساسي للنطاق',
    'schedule_baseline_management': 'إدارة الخط الأساسي للجدول الزمني',
    'cost_baseline_management': 'إدارة الخط الأساسي للتكلفة',
    'governance_plans': 'خطط الحوكمة',
    'plan_integration': 'تكامل الخطط',
    'plan_integration_desc': 'يتم دمج خطط الإدارة لضمان إدارة متسقة للخطوط الأساسية عبر جميع مجالات المشروع.',
    'management_plans': 'خطط الإدارة',
    'policies_procedures': 'السياسات والإجراءات',
    'schedule': 'الجدول الزمني',
    'resource_optimization_hub': 'مركز تحسين الموارد',
    'resource_plan': 'خطة الموارد',
    'resource_structure': 'هيكل الموارد',
    'responsibility_matrix': 'مصفوفة المسؤوليات',
    'job_descriptions': 'الوصف الوظيفي',
    'optimization': 'التحسين',
    'export_landscape_pdf': 'تصدير PDF بالعرض',
    'ram_raci_matrix': 'مصفوفة RAM / RACI',
    'intersection_wbs_personnel': 'تقاطع حزم عمل WBS والموظفين المعينين.',
    'responsible': 'مسؤول',
    'accountable': 'مساءل',
    'consulted': 'مستشار',
    'informed': 'مطلع',
    'accountable_requires_definition': 'المساءل (A) يتطلب تعريف دور معتمد',
    'risk_register': 'سجل المخاطر',
    'risk_assessment': 'تقييم المخاطر',
    'detailed_risk_sheets': 'أوراق المخاطر التفصيلية',
    'issue_log': 'سجل القضايا',
    'risk_audit': 'تدقيق المخاطر',
    'loading_risk_hub': 'جاري تحميل مركز المخاطر...',
    'change_management_hub': 'مركز إدارة التغيير',
    'total_change_requests': 'إجمالي طلبات التغيير',
    'approved_variations': 'التغييرات المعتمدة',
    'pending_review': 'قيد المراجعة',
    'total_cost_impact': 'إجمالي تأثير التكلفة',
    'change_request_register': 'سجل طلبات التغيير',
    'search_requests': 'البحث في الطلبات...',
    'new_request': 'طلب جديد',
    'back_to_hub': 'العودة للمركز',
    'create_request': 'إنشاء طلب',
    'request_id': 'رقم الطلب',
    'description_of_change': 'وصف التغيير',
    'justification': 'المبررات',
    'financial_impact': 'الأثر المالي',
    'time_impact_days': 'الأثر الزمني (أيام)',
    'po_number': 'رقم أمر الشراء',
    'variation_items': 'بنود التغيير',
    'net_impact': 'صافي الأثر',
    'new_contract_total': 'إجمالي العقد الجديد',
    'original_value': 'القيمة الأصلية',
    'edit_request': 'تعديل الطلب',
    'no_change_requests_found': 'لم يتم العثور على طلبات تغيير',
    'old_qty': 'الكمية السابقة',
    'new_qty': 'الكمية الجديدة',
    'in_review': 'قيد المراجعة',
    'quantity_cost': 'الكمية/التكلفة',
    'time': 'الوقت',
    'quality': 'الجودة',
    'other': 'أخرى',
    'preparer': 'المعد',
    'contractor': 'المقاول',
    'change_request_form': 'نموذج طلب التغيير',
    'dom_gov': 'نطاق الحوكمة',
    'dom_scope': 'نطاق النطاق',
    'dom_sched': 'نطاق الجدول الزمني',
    'dom_fin': 'نطاق المالية',
    'dom_stake': 'نطاق أصحاب المصلحة',
    'dom_res': 'نطاق الموارد',
    'dom_risk': 'نطاق المخاطر',
    'team_directory': 'دليل الفريق',
    'operating_agreement': 'اتفاقية التشغيل',
    'performance_assessment': 'تقييم الأداء',
    'input_arsenal': 'ترسانة المدخلات',
    'connected_data_extract': 'بيانات مستخرجة متصلة',
    'approval_integration': 'الاعتماد والتكامل',
    'governance_context': 'سياق الحوكمة',
    'tools_logic': 'الأدوات والمنطق',
    'output_tier': 'مستوى المخرجات',
    'archive_ready': 'جاهز للأرشفة',
    'digitally_verified': 'تم التحقق رقمياً',
    'cross_process_link_active': 'رابط العمليات المشترك نشط',
    'source_context': 'سياق المصدر',
    'ready_for_formal_sign_off': 'جاهز للتوقيع الرسمي والأرشفة',
    'refining_output_artifact': 'تحسين مخرجات العمل',
    'view_source_process': 'عرض العملية المصدر',
    'baseline': 'الخط الأساسي',
    'drive_sync': 'تزامن درايف',
    'live': 'مباشر',
    'uploading': 'جاري الرفع...',
    'generate_pdf': 'إنشاء PDF',
    'push_to_baseline': 'دفع إلى الخط الأساسي',
    'initial_process_state': 'حالة العملية الأولية',
    'standard_processing_only': 'معالجة قياسية فقط',
    'processing_logic': 'منطق المعالجة',
    'enterprise_governance_protocol': 'بروتوكول حوكمة المؤسسة',
    'automated_cloud_archival_plan': 'خطة الأرشفة السحابية الآلية',
    'zarya_creates_structure': 'سيقوم PMIS بإنشاء هيكل مخصص لهذا المشروع:',
    'enterprise_sync': 'تزامن المؤسسة',
    'items': 'بنود',
    'export_pdf_deliverable': 'تصدير مخرج PDF',
    'finalizing_resultant_artifact': 'نهائي مخرجات العمل',
    'awaiting_work_completion': 'في انتظار إكمال العمل',
    'note_read_only': 'ملاحظة: هذا العرض للقراءة فقط للحفاظ على "المصدر الوحيد للحقيقة".',
    'domain': 'النطاق',
    'focus_area': 'منطقة التركيز',
    'prepared_by': 'أعد بواسطة',
    'reviewed_by': 'روجعت بواسطة',
    'approved_by': 'اعتمدت بواسطة',
    'synchronizing_artifact': 'جاري مزامنة مخرجات العمل...',
    'drive_upload_failed': 'فشل الرفع إلى درايف',
    'business_case': 'دراسة الجدوى',
    'agreements': 'الاتفاقيات',
    'management_policies': 'سياسات الإدارة',
    'contract_agreements': 'اتفاقيات العقود',
    'advance_payment_bonds': 'سندات الدفع المقدم',
    'go_to_wbs_setup': 'اذهب إلى إعداد WBS',
    'repopulate_from_project_db': 'إعادة التعبئة من قاعدة بيانات المشروع',
    'project_management_pmis': 'نظام معلومات إدارة المشاريع الإنشائية',
    'unique_record_id': 'معرف السجل الفريد',
    'baseline_timestamp': 'الطابع الزمني للخط الأساسي',
    'all_rights_reserved': 'جميع الحقوق محفوظة.',
    'manage_statuses': 'إدارة الحالات',
    'all_tasks': 'جميع المهام',
    'my_tasks': 'مهامي',
    'add_task': 'إضافة مهمة',
    'assumption_constraint': 'الافتراضات والقيود',
    'issues': 'المشكلات',
    'meeting_actions': 'إجراءات الاجتماع',
    'search_tasks': 'البحث في المهام...',
    'task_label': 'المهمة',
    'assignee_label': 'المسؤول',
    'priority_label': 'الأولوية',
    'add_status': 'إضافة حالة',
    'status_name_placeholder': 'اسم الحالة...',
    'todo': 'للقيام به',
    'planning_status': 'التخطيط',
    'rfp': 'طلب عرض سعر',
    'tendering': 'المناقصة',
    'at_risk': 'معرض للخطر',
    'update_required': 'يتطلب تحديث',
    'domain_overview_desc': 'عرض أداء النطاق ومؤشرات الأداء والعمليات النشطة.',
    'navigation': 'التنقل',
    'enterprise_standard': 'معيار مؤسسي',
    'total_processes': 'إجمالي العمليات',
    'baseline_status': 'حالة الخط الأساسي',
    'view_process': 'بدء العملية',
    'this_month': 'هذا الشهر',
    'domain_kpi_index': 'مؤشر أداء النطاق',
    'standard_compliance': 'الامتثال للمعايير',
    'process_lifecycle': 'دورة حياة العمليات',
    'no_processes': 'لا توجد عمليات متاحة',
    'active_processes': 'العمليات النشطة',
    'project_context': 'سياق المشروع',
    'domain_kpis': 'مؤشرات أداء النطاق',
    'Initiating': 'البدء',
    'Planning': 'التخطيط',
    'Executing': 'التنفيذ',
    'Monitoring & Controlling': 'المراقبة والتحكم',
    'Closing': 'الإغلاق',
    'initiating': 'البدء',
    'planning': 'التخطيط',
    'executing': 'التنفيذ',
    'monitoring': 'المراقبة والتحكم',
    'closing': 'الإغلاق',
    '1.3.1_sched': 'تحديد مسار المشروع',
    '1.3.2_sched': 'تحديد الأنشطة الرئيسية',
    '2.3.1_sched': 'جدول تعريف الأنشطة',
    '2.3.2_sched': 'تسلسل الأنشطة',
    '2.3.3_sched': 'الجدول الزمني الرئيسي (غانت)',
    '2.3.4_sched': 'تقدير مدن الأنشطة',
    '2.3.5_sched': 'تطوير خط الأساس للجدول',
    '3.3.1_sched': 'إدارة تنفيذ الجدول',
    '3.3.2_sched': 'تحديث التقدم (غانت)',
    '3.3.3_sched': 'قائمة التقارير اليومية',
    '4.3.1_sched': 'مراقبة أداء الجدول',
    '4.3.2_sched': 'التحكم في تغيير الساعات',
    '5.3.1_sched': 'التحقق النهائي من الجدول',
    '5.3.2_sched': 'أرشفة سجلات الجدول',
    '2.3.3_sched_summary': 'مخطط غانت ومساحة العمل التفاعلية للجدول الزمني.',
    '1.3.1_sched_summary': 'تحديد خارطة الطريق عالية المستوى ومعالم المشروع الرئيسية.',
    '1.3.2_sched_summary': 'تفكيك مخرجات المشروع الأساسية إلى أنشطة أولية.',
    '2.3.1_sched_summary': 'تفكيك دقيق لعمل المشروع إلى أنشطة قابلة للتتبع.',
    '2.3.2_sched_summary': 'ربط الأنشطة وإنشاء تسلسل منطقي للعمل.',
    '2.3.4_sched_summary': 'تحديد الوقت المطلوب لكل نشاط في المشروع.',
    '2.3.5_sched_summary': 'إنشاء الجدول الزمني الرسمي وخط الأساس للمشروع.',
    '3.3.1_sched_summary': 'تنسيق إجراءات الفريق وتتبع التقدم اليومي.',
    '3.3.2_sched_summary': 'عرض الجدول الزمني التنفيذي مع التقدم الفعلي.',
    '3.3.3_sched_summary': 'سجلات يومية رسمية لأنشطة الموقع.',
    'new_daily_log': 'سجل يومي جديد',
    'update_daily_log': 'تحديث السجل اليومي',
    'incident_log': 'سجل الحوادث والعوائق',
    'reporting_date': 'تاريخ التقرير',
    'log_author': 'كاتب السجل / المراقب',
    'narrative_description': 'وصف سردي للعمل المنجز',
    '4.3.1_sched_summary': 'تحليل انحراف الجدول الزمني واستخدام إدارة القيمة المكتسبة.',
    '4.3.2_sched_summary': 'إدارة التعديلات على خط الأساس للجدول الزمني.',
    '5.3.1_sched_summary': 'الحصول على قبول أصحاب المصلحة للأداء النهائي.',
    '5.3.2_sched_summary': 'تجميع وأرشفة جميع سجلات الجدول الزمنات.',
    'foundation_center': 'مركز التأسيس',
    'foundation_center_desc': 'البيانات التأسيسية للمشروع ومركز البيانات الرئيسية للتحكم في كافة صفحات النظام.',
    'business_docs': 'وثائق الأعمال',
    'business_docs_desc': 'المبررات الاستراتيجية والاقتصادية للمشروع.',
    'feasibility_study_title': 'دراسة الجدوى',
    'expected_roi': 'العائد المتوقع على الاستثمار',
    'benefits_plan_title': 'خطة إدارة المنافع',
    'strategic_benefits': 'المنافع الاستراتيجية',
    'benefit_metrics': 'مقاييس الأداء للمنافع',
    'realization_period': 'المدة الزمنية لتحقيق المنافع',
    'contractual_obligations': 'الالتزامات التعاقدية',
    'add_agreement': 'إضافة اتفاقية/عقد',
    'no_agreements_added': 'لم يتم إضافة أي اتفاقيات بعد.',
    'templates_library': 'مكتبة القوالب',
    'knowledge_base': 'قاعدة المعرفة',
    'foundation_versions': 'سجل إصدارات البيانات التأسيسية',
    'master_data': 'البيانات الرئيسية',
    'design_hub': 'المخططات والهندسة',
    'design_hub_desc': 'المستودع المركزي لمخططات الأوتوكاد، النماذج ثلاثية الأبعاد، والمواصفات الهندسية.',
    'upload_dwg': 'رفع ملف أوتوكاد (.dwg)',
    'upload_3d': 'رفع نموذج ثلاثي الأبعاد',
    'blueprints': 'المخططات الهندسية',
    '3d_renderings': 'التصاميم ثلاثية الأبعاد',
    'technical_specs': 'المواصفات الفنية',
    'add_design_file': 'إضافة ملف تصميم',
    'no_designs_found': 'لم يتم رفع أي ملفات تصميم بعد.',
    'design_version': 'إصدار التصميم',
    'cad_viewer': 'عارض الكاد',
    'view_3d': 'عرض النموذج ثلاثي الأبعاد',
    'save_master_data': 'حفظ البيانات الرئيسية',
    'benefits_realization': 'تحقيق الفوائد',
    'foundation_insights': 'رؤى التأسيس',
    'eefs': 'العوامل البيئية',
    'opas': 'أصول العمليات',
    'scroll_to_today_summary': 'تمرير الجدول الزمني للتركيز على تاريخ اليوم الحالي.',
    'search_items_summary': 'تصفية القائمة حسب الوصف أو مركز التكلفة أو الموقع للعثور على حزم عمل محددة بسرعة.',
    'zoom_in_summary': 'زيادة دقة المخطط لعرض التفاصيل يوماً بيوم.',
    'zoom_out_summary': 'تقليل الدقة لرؤية الأشهر أو الأرباع في عرض واحد.',
    'import_data_summary': 'استيراد بنود جدول الكميات من إكسل أو PDF. يمكن للذكاء الاصطناعي استخراج التفاصيل تلقائياً.',
    'add_activity_summary': 'إنشاء نشاط مشروع جديد. تحديد المدة والميزانية والروابط بهيكل تقسيم العمل.',
    'column_settings_summary': 'اختر حقول البيانات التي تريد عرضها في جدول المهام (مثل التواريخ، SPI، التكلفة).',
    'overview_summary': 'العودة إلى لوحة تحكم النطاق للحصول على نظرة عامة عالية المستوى على الأداء.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // UI is always English LTR
    document.documentElement.lang = 'en';
    document.documentElement.dir = 'ltr';
  }, []);

  const t = (key: string) => {
    const text = translations['en'][key] || key;
    return stripNumericPrefix(text);
  };

  const th = (key: string) => {
    const text = translations['en'][key] || key;
    return stripNumericPrefix(text);
  };

  const isRtl = false;
  const isHelpRtl = false;

  return (
    <LanguageContext.Provider value={{ language: 'en', setLanguage: () => {}, t, th, isRtl, isHelpRtl }}>
      <div className="font-sans" dir="ltr">
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
